### ISSUE TITLE
Support of jginyue-x99m-plus

### ISSUE THREAD

**Issue by timmus31** [miyconst/Mi899#100]
Hello,

I saw that this MB is listed but without any bios, is it compatible with another MB?

Best regards,

**Comment by miyconst** [comment]
Hi. The version of JginYue X99M-Plus I tested was compatible with Machinist X99-RS9 BIOS and Huananzhi X99-8M-F but I forgot to add this compatibility in Mi899.

If you have the same revision you should be able to flash the BIOS by selecting Huananzhi X99-8M-F in Mi899.

The JginYue X99M-Plus BIOS compatibility is now updated in the app and will be available with the next release.
