### ISSUE TITLE
Support for  ZSUS  X99  P4

### ISSUE THREAD

**Issue by dangchuif16** [miyconst/Mi899#101]
HELLO  is there support   for  ZSUS  X99  P4

https://s.click.aliexpress.com/e/_DFaZQ5f

![image](https://github.com/miyconst/Mi899/assets/6435556/3b1ebb3b-c6da-463b-b264-7c24155d326e)

i don t  arrived to  adjust my bios  for detect  my  M2  NVME  SATA
THanks  for you  help   and is  there modified bios  
for this  motherboard

**Comment by miyconst** [comment]
So far I don't have any plans testing ZSUS boards but I have got myself a [Machinist X99-PR9](https://s.click.aliexpress.com/e/_DFJwURb) that looks very similar. The BIOS is most likely compatible as well, so stay tuned.

SATA / NVMe SSD support has nothing to do with Mi899 though. BIOS update won't help either, most likely you have to flip some physical jumpers (switches) on the motherboard.

**Comment by dangchuif16** [comment]
hello   thanks     maybe is similar  at  the motherboard   HUNANZHI X99 P4   : 
 http://www.huananzhi.com/en/more.php?lm=10&id=703
