### ISSUE TITLE
Help For Choose Correct BIOS for MACHINIST MR9A PRO

### ISSUE THREAD

**Issue by InterKode** [miyconst/Mi899#104]
Hello, I have a MACHINIST MR9A Pro motherboard https://s.click.aliexpress.com/e/_DlDVc7P I would like to update the BIOS and if possible choose a BIOS compatible with PCIe 16 4x4 to install this card : https://aliexpress.com/item/1005005987812379.html.

You can help me choose give me the correct BIOS reference I don't want to make a mistake and block the motherboard this is a first time for me. Thanks for your help.

**Comment by miyconst** [comment]
When it comes to the Chinese hardware there is no guarantee that anything will work as expected or as specified. I cannot guarantee that any of the available BIOS options will have proper support for PCI-E Bifurcation but you can test this BIOS: [MACHINIST X99-MR9A PRO MAX Custom BIOS from iEngineer](https://youtu.be/RI5bpvRTA_E?si=Qv2m4jLKe7CV2MKT).

**Comment by InterKode** [comment]
I downloaded Mi899-1.2.8 and saw a list of BIOSes in it, is there one that I could already use because I saw a tutorial video for updating using Mi899 and it seems simpler to me for me while waiting to understand what is explained in your video link I do not understand English well and I am not an expert in this field, and I sent a message to the seller of Ali Express I am waiting for that answer.

**Comment by InterKode** [comment]
You deleted my request before I even explained everything to you....

I downloaded Mi899-1.2.8 and saw a list of BIOSes in it, is there one that I could already use because I saw a tutorial video for updating using Mi899 and it seems simpler to me for me while waiting to understand what is explained in your video link I do not understand English well and I am not an expert in this field, and I sent a message to the seller of Ali Express I am waiting for that answer. 

----- Mail original -----
De: "Kostiantyn Cherniavskyi" ***@***.***>
À: "miyconst/Mi899" ***@***.***>
Cc: "1QC1Q" ***@***.***>, "Author" ***@***.***>
Envoyé: Dimanche 21 Janvier 2024 22:13:45
Objet: Re: [miyconst/Mi899] Help For Choose Correct BIOS for MACHINIST MR9A PRO (Issue #104)





Closed #104 as completed.

**Comment by miyconst** [comment]
I do not recommend messing with the BIOS unless you understand what and why you are doing. Mi899 helps with Turbo Boost Unlock it guarantees no specific BIOS or motherboard features.

**Comment by InterKode** [comment]
I understand the BIOS, it's with English that I have difficulty.
I saw this video on Youtube (https://www.youtube.com/watch?v=zWc6rHQ2QP0) which explains that with Mi899 I can overclock the processor Boost the CPU but I was wondering if it was possible for PCIe .
And to boost my MR9A Pro via Mi899, what should I choose from the BIOS list?
Stock Huananzhi X99-8M-F, TP will work or I have to take another one

Thank you for your help and advice.

----- Mail original -----
De: "Kostiantyn Cherniavskyi" ***@***.***>
À: "miyconst/Mi899" ***@***.***>
Cc: "1QC1Q" ***@***.***>, "Author" ***@***.***>
Envoyé: Dimanche 21 Janvier 2024 22:24:28
Objet: Re: [miyconst/Mi899] Help For Choose Correct BIOS for MACHINIST MR9A PRO (Issue #104)





I do not recommend messing with the BIOS unless you understand what and why you are doing. Mi899 helps with Turbo Boost Unlock it guarantees no specific BIOS or motherboard features.

**Comment by miyconst** [comment]
>Stock Huananzhi X99-8M-F, TP will work or I have to take another one

This would be my best guess but as I have already said I can guarantee absolutely nothing when it comes to the AliExpress hardware. It may work but also may brick your motherboard.

**Comment by InterKode** [comment]
Ok thank you I will try, I know that if it crashes it is my fault that the computer will certainly not reboot and that I would have earned the right to disassemble the chip to reflash the BIOS via the CH341a and spank the Chinese...Lol
Thank you for any good day or evening at my place it's night!

----- Mail original -----
De: "Kostiantyn Cherniavskyi" ***@***.***>
À: "miyconst/Mi899" ***@***.***>

Stock Huananzhi X99-8M-F, TP will work or I have to take another one 

This would be my best guess but as I have already said I can guarantee absolutely nothing when it comes to the AliExpress hardware. It may work but also may brick your motherboard.
