### ISSUE TITLE
support Machinist X99-P3

### ISSUE THREAD

**Issue by phil-audio** [miyconst/Mi899#106]
Good morning, 
I then come back to the topic of bios , That it bios could well go on this card, I would like to be able to modify it.
and thank you again for your work on the development of mi899
If she could also be part of the cards that are in MI899, that would be great.

Hello from Belgium , Phil
![machinist x99-p3](https://github.com/miyconst/Mi899/assets/38981532/43848c43-0b3f-4e09-ad7b-964f932c6990)

**Comment by miyconst** [comment]
The motherboard looks almost one-to-one with Machinist X99-PR9, so if you are willing to risk, you can try to flash X99-PR9 BIOS.

**Comment by miyconst** [comment]
DDR3 and DDR4 use different voltage, different IMC within the CPU, some motherboards support both, DDR3 and DDR4, these two do not interleave.

**Comment by phil-audio** [comment]
Good morning,
this card unfortunately only supports DDR3, so it is prudent not to flash with the bios of the x99-pr9 which is in DDR4

**Comment by TianjingChina** [comment]
![360截图20240623234420443](https://github.com/miyconst/Mi899/assets/173776251/33538182-8899-4347-9757-c9843a8fe9de)
![360截图20240623234446769](https://github.com/miyconst/Mi899/assets/173776251/95c0ce0b-74f9-4a30-8886-ecb675ac514d)

帮我把BIOS改成中文的   原BIOS发不上来

**Comment by miyconst** [comment]
>帮我把BIOS改成中文的   原BIOS发不上来         求帮助  改成中文的

@TianjingChina why would you ever want your BIOS to be in Chinese?

**Comment by TianjingChina** [comment]
全英文不太懂 M2不识别 调了好多 不开机 太费劲了



在 2024-06-25 18:55:42，"Kostiantyn Cherniavskyi" ***@***.***> 写道：

帮我把BIOS改成中文的 原BIOS发不上来 求帮助 改成中文的

@TianjingChina why would you ever want your BIOS to be in Chinese?

**Comment by TianjingChina** [comment]
M2不识别  调了好几次  不开机  看不懂Message ID: ***@***.***>

**Comment by TianjingChina** [comment]
给你发个原BIOS还被退信

**Comment by TianjingChina** [comment]
![b1418780acc5fa398f5225ed1db6e70](https://github.com/miyconst/Mi899/assets/173776251/195d1dfb-0f33-44ca-9e77-c37e54b6f37b)
    关了不开机

**Comment by TianjingChina** [comment]
![58b8563b989be643f018e19e0013313](https://github.com/miyconst/Mi899/assets/173776251/17e619ef-4ad1-4a53-a964-a148513b03e7)
