### ISSUE TITLE
X99-F8 BIOS PEI moded with Turbo Unlock -50/50 and ReBar

### ISSUE THREAD

**Issue by wavypalasbabys** [miyconst/Mi899#107]
As it says in the title, I just moded a X99-F8 BIOS PEI with Turbo Unlock -50/50 + ReBar. It works well with my X99-8M (non F), I don't know if it works with X99-F8, but it should works.
[X99-8M-BIOS-TU-ReBAR.zip](https://github.com/miyconst/Mi899/files/14211062/X99-8M-BIOS-TU-ReBAR.zip)

**Comment by wavypalasbabys** [comment]
There's some proof of working
![IMG_7171](https://github.com/miyconst/Mi899/assets/152556984/01631972-cd46-4f98-8165-39a2bf8c139b)
![IMG_7172](https://github.com/miyconst/Mi899/assets/152556984/fb9d9dac-c27b-45a8-93d8-300770aa0ebc)
![IMG_7173](https://github.com/miyconst/Mi899/assets/152556984/3a1f47a5-e8bc-4218-86f9-3f35e2abdba1)

**Comment by miyconst** [comment]
Thanks @wavypalasbabys, the BIOS has been added to the M899 collection and will be available with the next release.

**Comment by zombinen** [comment]
the bios works with Huanazhi X99 - TF (C612 chipset)?

**Comment by 187Penguin** [comment]
Would this work on a Machinist X99 K9?
