### ISSUE TITLE
Machinist x99 e5 m9a pro

### ISSUE THREAD

**Issue by snagglep** [miyconst/Mi899#109]
I have this board with an e5 2699 v3 and tried all the bios from your app and they all lock up after a few minutes testing also the turbo unlock isn't working as the cpu fluctuates between lo and high.
Do you have any ideas I can do.
Thanks

**Comment by miyconst** [comment]
This question has nothing to do with Mi899 app. If you need help troubleshooting your hardware - please join my Discord.

https://discord.gg/nV4zY7rF
