### ISSUE TITLE
Jingsha X99 D4 Plus Inquiry

### ISSUE THREAD

**Issue by Bob-The-Ross** [miyconst/Mi899#110]
Hello,

I am wondering if you have plans to cover the Jingsha X99 D4 Plus motherboard? It looks like it was released in May 2023 and has a couple more VRM phases.

This is the Aliexpress page: https://www.aliexpress.com/item/1005006144373686.html

![Screenshot 2024-02-19 at 16-45-56 147 2C$ 41% OFF JINGSHA X99 D4 PLUS LGA 2011 3 XEON X99 Motherboard with Intel E5 2666 V3 With 2 16G DDR4 RECC Memory Combo Kit Set NVME NGFF - AliExpress](https://github.com/miyconst/Mi899/assets/44041137/36ffabab-26cc-46aa-84cb-78ea37277993)

**Comment by miyconst** [comment]
Hi there. This JingSha motherboard looks interesting, if I get a chance I will test it but for now I don't have any immediate plans.

**Comment by Bob-The-Ross** [comment]
Great I will keep an eye out if you decide to test it one day, I appreciate your reply!
