### ISSUE TITLE
Stuck at code 68

### ISSUE THREAD

**Issue by ToanHaHe** [miyconst/Mi899#111]
I undervolt and unlock and its stuck at code 68. specs: X99 TF-Q, 2696v3.

**Comment by miyconst** [comment]
This has nothing to do with the Mi899 app itself, you can use this page to diagnose post codes: [Post Codes of Chinese LGA 2011-3 X99](https://miyconst.github.io/hardware/cpu/intel/motherboard/2023/11/18/chinese-x99-post-codes.html).
