### ISSUE TITLE
TBU not working for long period of time after flashing in HZ x99-TF with 2678 v3

### ISSUE THREAD

**Issue by EsteveNoguera** [miyconst/Mi899#114]
Hello,

I have been trying recently to turbo unlock my mobo. I decided to also go with some undervolt at the same time since I was flashing the bios. After reboot I check CPU-Z, Task Manager and HWMonitor they report 3.2 GHz for a minute or two but then it goes to 1.5-2 GHz. This issue happens as well with a BIOS without any undervolting. 

Tried to run some games to see if frequency can go up but it doesn't. I am also checking temperatures in HWMonitor if cpu is thermal throttling but I do not see any high temperatures. 

Is there anything I am missing? I got a CH314a reprogrammer in case is needed. 

Mobo: Huananzhi X99-TF
Chipset: C612
LPCIO: NCT6779
Tested roms: Stock Huanzhi X99-F8 TU FFS/Stock Huanzhi X99-F8 TU FFS -70/50 mV
Tool for flashing: FPT 9.1
CPU: E5-2678 v3
GPU: 3060 Ti (BIOS updated for ReBar)

Edit: Reflashed Stock X99-TF back.

Thank you in advance!

**Comment by miyconst** [comment]
Hello. The issue described has nothing to do with Mi899 application itself. Please [join my Discord](https://discord.gg/Epv8UQjr) if you need help debugging your setup.
