### ISSUE TITLE
huananzhi-x99-8m-f.tp.s3tt.5050 not recognize my rx 570 8GB

### ISSUE THREAD

**Issue by eonlineok** [miyconst/Mi899#117]
Hi, the huananzhi-x99-8m-f.tp.s3tt.5050 not recognize my rx 570 8GB. Any solution for this problem?

Specs:
QIYIDA X99 M9
2630 v4
16gb drr4
Windows 10

Note: when I attach the rx 570 the motherboard makes a sound and five beeps and another sound. With a gt710 works well.

Original bios: 

[hz-x99-8m-f-20240408-174613.zip](https://github.com/miyconst/Mi899/files/14911324/hz-x99-8m-f-20240408-174613.zip)

Thanks a lot.
All the best.

**Comment by eonlineok** [comment]
What is manual UEFI installation required?

**Comment by miyconst** [comment]
Does the motherboard recognize your RX 570 with the original BIOS?

**Comment by eonlineok** [comment]
No =(

**Comment by miyconst** [comment]
Then it's a typical compatibility issue of the Chinese X99 motherboards, you can try to disable CSM and/or BIOS from iEngineer for Machinist X99-RS9 or X99-MR9A motheboards.

More info about the BIOS in my review videos:
- [Machinist X99-MR9A (Pro) – my favorite LGA 2011-3 motherboard from AliExpress](https://youtu.be/kEn30kEkQes).
- [Qiyida X99-QD4 (G629A) – detailed review of the motherboard](https://youtu.be/-JENPUG7zCY).

**Comment by eonlineok** [comment]
Flashed the X99-MR9A, disabled CSM and still have the problem.

**Comment by miyconst** [comment]
>Flashed with the X99-MR9A bios, disabled CSM and still have the problem.

Unfortunately, I can't help here, it's a compatibility issue with the Chinese X99 motherboards.

**Comment by eonlineok** [comment]
Thanks, I bought a Jxz Radeon Rx580 (2048sp) hope this card works well.

All the best.

**Comment by eonlineok** [comment]
@miyconst my 2x8gb adata ad4u32008g22-sgn not works with the bios and the motherboard, any idea?
