### ISSUE TITLE
Bios stock on Huananzhi x99-TF

### ISSUE THREAD

**Issue by FlauzerOriginal** [miyconst/Mi899#119]
@Miyconst Thanks for your work.
I take the **Huananzhi x99-TF** as a reference.

If I understand correctly, the changes and optimizations we find start from rather "_dated_" bios (2019-20??). Right now I use hz-x99-f8.mi8.rom. date 10/27/2019.

However, (again for the Huananzhi x99-TF), we find other "Stock" BIOSes X99-TFV3.0**22-08-30**.rar and X99-TFV3.0JX**22-09-16**.rar (with several new options). (http://www.huananzhi.com/en/more.php?lm=10&id=306)
Without changing anything I end up with the 2690V3 at 3.5Ghz, but I am not able to understand the validity of this update, for example whether the parameters do not put too much strain on the VRM components, and so on.

Is there any reason why they don't belong to the Mi899 program as "stock"? Is it possible to find them manipulated with the recent changes (Resize Bar, etc...) or are the paths completely "different"?
I apologize if these questions are not strictly issues.

**Comment by miyconst** [comment]
The new X99-TF/F8/T8 BIOS is not in Mi899 because it was not tested by me, you are still free to try it if you wish so.

**Comment by FlauzerOriginal** [comment]
thx Kostiantyn, i'll try to see the differences in a better way and more technically, in my free time... (not much to be honest). I briefly saw that there is the secure boot option, a few points less in CPUZ, different report temperature values ​​Nuvoton NCT6793D AUXTIN 1,2,3 with HWINFO...
In the meantime, congratulations and thanks for your videos and the information you share, they are very useful. Number one.

**Comment by miyconst** [comment]
>thx Kostiantyn, i'll try to see the differences in a better way and more technically, in my free time...

Be careful. Different revisions of these motherboards require different BIOS, so if you flash a wrong version you will brick your motherboard, so prepare an external flash programmer before messing with the BIOS.
