### ISSUE TITLE
Jginyue Titanium D4 motherboard sata/m2 jumper

### ISSUE THREAD

**Issue by edwardyuanslalom** [miyconst/Mi899#120]
Hello there,

Love your work on these motherboard! 

Now I have Titanium D4 motherboard that I can't get my head around getting SATA to work, attached SATA/M2 jumper on the motherboard. 

![20240509_075214](https://github.com/miyconst/Mi899/assets/147349104/de80544e-d52c-453c-89e5-c033f90721ba)

With the current configuration (default) only m2 is working, none of the SATA ports are working. 

Now how do I set the jumper if I want to use both SATA and M2 at the same time? Alternatively how do I set it to SATA only if I am not using M2 completely?

Looking forward and thanks so much for your reply!

**Comment by miyconst** [comment]
Ok, from what I see on the diagram, it's two jumpers per slot, two slots, four jumpers in total.

The numers go like this:

| | |
|-|-|
|1|2|
|3|4|
|5|6|

The current position is 3-5 and 4-6 which is the SATA mode. Why it doesn't work - another question.
