### ISSUE TITLE
Support for Huananzhi x99-8D4

### ISSUE THREAD

**Issue by florentinuskev** [miyconst/Mi899#123]
Hi I am wondering if there is any bios mod for Huananzhi x99-8D4.

Thank you so much for this bios mod, I learn a lot from you!.

**Comment by miyconst** [comment]
So far I have no such modifications and I can't afford buying X99-8D4 just for the sake of a review.

The [motherboard costs almost $200](https://s.click.aliexpress.com/e/_DBNESJd) with delivery to Sweden while the feature set is a big cut down from the X99-F8D.

[![](http://www.huananzhi.com/en/attach/202309/1694578372145469602.png)](https://s.click.aliexpress.com/e/_DBNESJd)
