### ISSUE TITLE
MACHINIST-RS9 X99 V1.1 bios

### ISSUE THREAD

**Issue by manotroll** [miyconst/Mi899#124]
with Q87 chipset
the bios says it's from 2023
on the board and in the bios they say it is V1.1
has separate Resizable BAR and Above 4G mode
However, when turning on UEFI mode, it stops starting
As I'm using it on the RX480, maybe that could be it
when resetting the cmos returns to normal
[machinist-x99-rs9-20220507-025312.zip](https://github.com/user-attachments/files/15936221/machinist-x99-rs9-20220507-025312.zip)

**Comment by miyconst** [comment]
Thank you for the BIOS file but I don't add unverified options to my collection. If I get a chance to test it - it will be added to Mi899,

**Comment by EnockMonteiro** [comment]
Obrigado estava precisando disso
