### ISSUE TITLE
Bios compatibility with JINGSHA X99 D8

### ISSUE THREAD

**Issue by nelu** [miyconst/Mi899#126]
I tried flashing huananzhi-x99-tf.bi.rbe.mi8.rom on JINGSHA X99 D8 motherboard, since its was in the bios compatibility list in the app, but managed to brick the board. 
![bioses-rbe](https://github.com/miyconst/Mi899/assets/3987091/2a5e966b-ec77-4c9d-8d0d-ddb7a4d728b5)

Used a eeprogramer to unbrick no worries (exactly like in your video)

Can you review the bios version for the board, to check if it works properly, or to remove it from the compatibility list.

Also if you need any help, im available for testing bioses on this particular motherboard.
Thanks.

**Comment by miyconst** [comment]
There are several different revisions of Huananzhi X99-TF/F8/T8 as well as different revisions of JingSha X99-D8. Chinese update these versions without any prior notification and backwards compatibility.

If I ever get my hands on the latest JingSha X99-D8 - I will test it and update Mi899,

**Comment by nelu** [comment]
I got my JingSha X99-D8 around October 2020, a few months after you released your first videos about the board, so its not a recent revision of motherboard.

**Comment by miyconst** [comment]
>I got my JingSha X99-D8 around October 2020, a few months after you released your first videos about the board, so its not a recent revision of motherboard.

In that case we have some other incompatibility because all JingSha X99-D8 motherboards I had were compatible with X99-TF BIOS.

**Comment by TianjingChina** [comment]
编程器刷回原版BIOS   试试
