### ISSUE TITLE
JGINYUE x99-8D4/2.5G

### ISSUE THREAD

**Issue by RigerCrows** [miyconst/Mi899#128]
Can you unlock the CPU in this motherboard? I couldn't find it in your system. It has 512 GB RAM support. The one I have in black has 256 GB RAM support and it has red and black colors.

**Comment by miyconst** [comment]
All supported motherboards and BIOS options are already in Mi899. Please let me know if you would like to sponsor a motherboard review by providing a JginYue X99-8D4/2.5G sample so I can add its BIOS and support to Mi899.

**Comment by RigerCrows** [comment]
> Desteklenen tüm anakartlar ve BIOS seçenekleri zaten Mi899'da. BIOS'unu ve Mi899'a desteğini ekleyebilmem için bir JginYue X99-8D4 / 2.5G örneği sağlayarak bir anakart incelemesine sponsor olmak isteyip istemediğinizi lütfen bize bildirin.

I'm sorry I can't sponsor you, I was just wondering if it could be added.

**Comment by jimthedj65** [comment]
I have recently acquired this board and its a bit erratic. I have a 750w power supply with dual 2699v4 TDP 145w and a Intel Arc 380 with 75w. 8 x 32GB ECC samsung ram at 4.6 watts max per chip with a total of about 550 watts with hard disks and SSD/NVME drives. so well within the PSU spec.

It has the standard AMI 5.11 BIOS and looking at Jginyue site my bios is more up to date which makes me think that it might support a different bios as they have a 1.2 version of this board

I haven't connected it to the internet and it boots sometimes and sometimes it just hangs, I would appreciate any advice on whether this board is just faulty or if an ME update will solve the issues?

happy to provide a sample of this board, I am based in the philippines.

I will give your software a go, my only other option is connect to internet or RMA
