### ISSUE TITLE
Paypal link broken

### ISSUE THREAD

**Issue by Nova-Robotics** [miyconst/Mi899#129]
Hey good buddy, I tried to buy you a beer but the Paypal link in Mi899 is broken.  Update that so I can send you some bucks for your hard work!

**Comment by miyconst** [comment]
Hi there and thank you for the support. Could you please specify what kind of error you get, what country you are trying to donate from, and which language version of Mi899 you used?

I did a quick check of a couple of links, and they all seemed to work.

If nothing works, my PayPal email is the same as the GitHub username: `miyconst @ gmail.com`.
