### ISSUE TITLE
Turbo Boost doesn't stay on.

### ISSUE THREAD

**Issue by uhyeahright** [miyconst/Mi899#130]
After applying the huananzhi-x99-8m-f.tp.s3tt.10050.rom to my Machinist X99-MR9A motherboard, then setting the bios to defaults. The turbo boost doesn't last longer than a minute.

The cpu does have a cpu cooler and the cpu stays under 38 degrees C, even under load.

Am I doing something wrong?

**Comment by miyconst** [comment]
Most likely you did everything right but the CPU hits the TDP limit and drops its clock, you can try disabling some CPU cores if you want higher frequency.
