### ISSUE TITLE
Envinda KN-X99D4M4 Review Inquiry

### ISSUE THREAD

**Issue by Bob-The-Ross** [miyconst/Mi899#131]
Hi Miyconst,

I am curious if you would be interested in reviewing the Envinda KN-X99D4M4 motherboard which is sold here: 

https://www.aliexpress.com/item/1005006661753244.html#nav-review

From my testing, it has an authentic C612 chipset alongside 2x NVMe SSD ports and decent quality VRMs (supposedly 8-phase). Unfortunately I have not been able to get overclocking working on this motherboard but would be happy paying money for an overclocking bios to be developed if you know anyone willing to! 

I believe it's overall a potentially great budget motherboard for turbo unlock and possibly unlocked cpu overclocking.

There is also an AIGO clone X99 motherboard available on ali: 

[![](https://ae-pic-a1.aliexpress-media.com/kf/Sd0cb1f7763954f20bdb648db9e0a7018d/Envinda-X99-d4-LGA-2011-3-Desktop-motherboard-M-2-NVME-slot-Support-DDR4-ECC-SATA3.jpg_.webp)](https://s.click.aliexpress.com/e/_DFdyLUL)

**Comment by antracks26** [comment]
I have bought similar motherboard x99D4M4 v1.13 (sold as x99 D4M). I dont know too how turbo unlock.

**Comment by miyconst** [comment]
@Bob-The-Ross you can check [BIOS options from iEngineer](https://www.patreon.com/biosiengineer/shop).

**Comment by miyconst** [comment]
@antracks26 please follow this guide: [Xeon E5 V3 Turbo Boost Unlock with S3TurboTool](https://miyconst.github.io/hardware/cpu/intel/2023/11/18/tbu-s3turbotool.html).

**Comment by antracks26** [comment]
Thank you for your reply. I will take the time to read and translate as I don't want to make any mistakes. I'll come back after I've tried it.

**Comment by antracks26** [comment]
Hello again, i dont understand at start how load an image bios. Should i save my bios by afuwinx64 or ftpw 64 ? and at the end i dont understand how flash a bios. With your method i dont see how doing by click on mi899. 
thx advance and sorry for my bad  english.

**Comment by miyconst** [comment]
@antracks26 please watch this video: [🇬🇧 Mi899 – X99 Tool Set | read, write BIOS & unlock turbo-boost with a few mouse clicks](https://youtu.be/bO2t790vhg8?si=tFwwlMFbBO_bRveG).

**Comment by antracks26** [comment]
Hi again; i have finally unlock the turbo boost on this motherboard. I must say that i have use the method of a video youtube by download a file Unlock (51mo). For now, the pc is stable and not hot. Iwill test in games or other.
Processor frequencies often vary and are not always all at 3.6ghz, nevertheless, it's already much better than when I started, and that's where my expertise ends.
