### ISSUE TITLE
Xeon e5 2696 v3 not turboing at max frequency even in ST or with no load

### ISSUE THREAD

**Issue by theSilver32** [miyconst/Mi899#132]
Hi everyone, I'm posting this because my xeon E5 2696 V3 isn't turning at its max speed. It's rated to go to 3.8 GHz, but I am only able to get 3.4 GHz in single core and in all core when no load is applied. In windows at idle it sits at 3.4 on all cores and under load, in multi core I am able to get it to 2.9/3.0 GHz. I am using a jingsha x99 d8 with huananzhi f8 bios with s3turbo hack and -90/60 on voltage. In CPU z I can see the CPU is rated for 3.8 and I don't know how to solve or what is causing the issue. If anyone could help me answering this it would be really appreciated. Thx in advance and for the work you do.
![Screenshot (71)](https://github.com/user-attachments/assets/a3879143-3274-46da-b707-1ff78cab151b)

**Comment by miyconst** [comment]
Hi. This question is not related to Mi899, please join my Discord if you need help or assistance: https://discord.gg/8vYdUqWT

Also, please watch this video: [Turbo Boost Unlock in 2023 – everything you need to know and more](https://youtu.be/IsgBQ0ZMxYY?si=pHp20a9Gydx6fCtY).
