### ISSUE TITLE
Title: Will there be a BD4 version of the Huananzhi LGA 2011 v3 motherboard?

### ISSUE THREAD

**Issue by hectoruelo** [miyconst/Mi899#134]
I would like to know if there are any plans to release a new version of the Huananzhi BD4 motherboard for the LGA 2011 v3 socket. I am currently using the DB4 version and am interested in learning if there will be an updated or new version of the BD series.

Additionally, I’ve noticed that there are several functional BIOS versions available on various websites, such as  https://github.com/Koshak1013/HuananzhiX99_BIOS_mods/tree/master/Huananzhi%20X99-BD4 or https://xeon-e5450.ru/socket-2011-3/huananzhi-x99-bd4/ . 

It would be great to know if any of these will be supported in future versions. 

Thank you in advance for any information.

**Comment by miyconst** [comment]
Hi. So far there are no plans for X99-BD4 motherboard.
