### ISSUE TITLE
Machinist MR9A MAX Professional

### ISSUE THREAD

**Issue by donotknowwhatiamdoing** [miyconst/Mi899#135]
Hello, I have a problem, when I want to create the dump I get the following error message, although I start as administrator.

PMXUtil: Error during PMX Call: idrvdll.dll!IDRVInstallDriver(): Failed to start loaded service err: -2146762484

Error 284: Fail to load driver (PCI access for Windows).
Tool needs to run with an administrator priviledge account.
Thank you for using Mi899.

I am very much looking forward to your support.

Best regards
Terry

**Comment by donotknowwhatiamdoing** [comment]
Hello, thank you very much for the quick reply. I'll do it that way then.

I have an Intel Xeon E5-2690 V4 @2.60GHz can it be overclocked?

**Comment by donotknowwhatiamdoing** [comment]
Okay, then that's no good for me. 
Which CPUs are open? The V3?

**Comment by miyconst** [comment]
Please watch this video: [Turbo Boost Unlock in 2023 – everything you need to know and more](https://youtu.be/IsgBQ0ZMxYY?si=0I8rpGdzdjD1e_k8).

**Comment by donotknowwhatiamdoing** [comment]
Thank you very much!

**Comment by chs12345** [comment]
Are you using windows 11?
I got this problem too when I switched to 11.
I recently downgraded OS to win 10 and fptw works now.
