### ISSUE TITLE
Support for jingsha X99 8D3?

### ISSUE THREAD

**Issue by qb697236** [miyconst/Mi899#138]
![ChMkLGYXkrmIOJz7AARgUbRmiRIAAc2xQEvs9kABGBp948](https://github.com/user-attachments/assets/36135e84-2bcf-450e-8277-1e2992b33fa8)
Is there any plans for this motherboard？Thanks

**Comment by miyconst** [comment]
As far as I know, this is the same motherboard as the already supported JingSha X99-D8 but with DDR3 memory slots. No extra testing is planned so far.
