### ISSUE TITLE
Huananzhi X99-TF vs Huananzhi X99-F8

### ISSUE THREAD

**Issue by paulocmarques** [miyconst/Mi899#22]
Are the Huananzhi x99-TF and Huananzhi x99-F8 BIOSes interchangeable? When I select the Huananzhi x99-TF in the Mi899 tool, the TF and F8 BIOS are listed together. Is this right? Can I use, for example, the BIOS "Stock Huananzhi X99-F8 BIOS, TU FFS" without problems on the Huananzhi x99-TF? Or another with TURBO UNLOCK?

**Comment by miyconst** [comment]
Yes, Huananzhi X99-TF / X99-T8 / X99-F8 all have interchangeable BIOS.
