### ISSUE TITLE
Add Kllisre x99-d4 BIOS with turbo boost unlock

### ISSUE THREAD

**Issue by hvintik** [miyconst/Mi899#23]
Hello,

Can you please add a rom for Kllisre x99-d4 with the turbo boost unlock?

BTW, I've tried to flash x99-f8 bios but something is wrong with UEFI (it does not see boot devices), I could only boot Windows after I removed and installed a CMOS battery back.

Thanks in advance.

Thank you,

**Comment by miyconst** [comment]
Kllisre X99-D4 motherboard is compatible with the Huananzhi X99-F8 BIOS, thus I see no reason to create X99-D4 specific modifications. The UEFI boot issue is present in both BIOS versions and you can try to workaround it by disabling Legacy mode for your storage devices when using the X99-F8 BIOS.

If you would want to have the original X99-D4 BIOS modified for Turbo Unlock, it's very easy to perform, and here is a guide: [Xeon E5-2600 V3 Turbo Boost Unlock](http://www.miyconst.com/Blog/View/2081/xeon-e5-2600-v3-turbo-boost-unlock).

**Comment by hvintik** [comment]
Thanks for the tip.

I've just tried to switch the CSM setting to use UEFI only and it worked.
Looks like I did not notice this since on the original bios it was UEFI by default.

**Comment by themmorpgboss** [comment]
> Kllisre X99-D4 motherboard is compatible with the Huananzhi X99-F8 BIOS, thus I see no reason to create X99-D4 specific modifications. The UEFI boot issue is present in both BIOS versions and you can try to workaround it by disabling Legacy mode for your storage devices when using the X99-F8 BIOS.
> 
> If you would want to have the original X99-D4 BIOS modified for Turbo Unlock, it's very easy to perform, and here is a guide: [Xeon E5-2600 V3 Turbo Boost Unlock](http://www.miyconst.com/Blog/View/2081/xeon-e5-2600-v3-turbo-boost-unlock).

Would it work with kllisre d4 x99h v1.31 sorry im new to this and dont know much about it

**Comment by miyconst** [comment]
>Would it work with kllisre d4 x99h v1.31 sorry im new to this and dont know much about it

No, this one is 100% not compatible with X99-F8 BIOS.

**Comment by warryblack** [comment]
hi ,i m looking for efi folder ,fore klilisre x99 d4 dual cpu ,i can not complet montery instal

**Comment by pauloplz** [comment]
> > Funcionaria com kllisre d4 x99h v1.31, desculpe, sou novo nisso e não sei muito sobre isso
> 
> Não, este não é 100% compatível com o BIOS X99-F8.

por favor voce poderia disponibilizar uma verção de bios de llisre d4 x99 v.2/2020
