### ISSUE TITLE
Update Machinist X99z V102 BIOS-iEngineer to latest version

### ISSUE THREAD

**Issue by rafaelreis-r** [miyconst/Mi899#24]
Hey @miyconst!

It would be great to have latest release [C612RD24](https://github.com/BIOS-iEngineer/MACHINIST-X99ZV102 ) from BIOS-iEngineer in Mi899 with TU, FFS, Undervolt.

I'm happy to help and do the work of modding the BIOSes following Mi899 release pattern:

![image](https://user-images.githubusercontent.com/57492577/102246757-d9efd480-3edd-11eb-8b02-667a9240f81e.png)

However, although I'm really advanced with computers, hadware, coding, systems administration, I never have modded a BIOS before. If you could point out a guide and provide a list of your optimal settings, I can maybe make the modifications and test them on my board, and then make a Pull request here. 

Please let me know if I can help!

**Comment by miyconst** [comment]
Hello @rafaelreis-r and thank you for the proposed help, I would really appreciate it.

Here you can find my guides how to implement a Turbo Boost Unlocked BIOS: [Xeon E5-2600 V3 Turbo Boost Unlock](http://www.miyconst.com/Blog/View/2081/xeon-e5-2600-v3-turbo-boost-unlock).

You can also investigate this guide (in Russian), which claims to preserve Sleep Mode even with Turbo Boost Unlock implemented, but I have not yet tested it myself: [Добавляем анлок в биос раз и навсегда через S3TurboTool](https://xeon-e5450.ru/socket-2011-3/e5-2600-v3/dobavlyaem-anlok-v-bios-raz-i-navsegda-cherez-s3turbotool/).

**Comment by miyconst** [comment]
The latest [Machinist X99Z BIOS from iEngineer](https://github.com/BIOS-iEngineer/MACHINIST-X99ZV102) has been added and released in the 1.1.0 version.

**Comment by rafaelreis-r** [comment]
Awesome. Thank you. Sorry I couldn't get to this sooner. Had to go away for the holidays due to increasing restrictions with the pandemic, was only going to tackle it by Jan 4th. 
Again, awesome work!
