### ISSUE TITLE
New motherboard Kllisre X99 D4

### ISSUE THREAD

**Issue by ancarvmed** [miyconst/Mi899#26]
new motherboard Kllisre x99 d4, link attached, hope you can support this motherboard soon.

[https://es.aliexpress.com/item/4000974911783.html?spm=a219c.12010612.8148356.34.ca1271d85wRomB](url)

Thank you

**Comment by miyconst** [comment]
This is yet another revision of the very low quality PlexHD / X99-Turbo / Atermiter motherboard. Due to its low quality I do not plan to review or support this board. I also do not recommend anyone to buy this board.

**Comment by ancarvmed** [comment]
I have a problem, I have bought that board and I would like to unlock turbo boost, how can I do it?

Thank you.

**Comment by miyconst** [comment]
You can follow my and only my guides:

- [Xeon E5-2600 V3 Turbo Boost Unlock](http://www.miyconst.com/Blog/View/2081/xeon-e5-2600-v3-turbo-boost-unlock).
- [Добавляем анлок в биос раз и навсегда через S3TurboTool](https://xeon-e5450.ru/socket-2011-3/e5-2600-v3/dobavlyaem-anlok-v-bios-raz-i-navsegda-cherez-s3turbotool/).

**Comment by ancarvmed** [comment]
What motherboard do you recommend for a 2678 v3?

Thanks for your help, you do a great job.

Thank you.

**Comment by miyconst** [comment]
I would recommend Huananzhi [X99-TF](https://s.click.aliexpress.com/e/_9G9w65) / [X99-F8](https://s.click.aliexpress.com/e/_AcVXvf) / [X99-T8](https://s.click.aliexpress.com/e/_AKwpQt) or JingSha [X99-D8](https://s.click.aliexpress.com/e/_A0FPJ7).
