### ISSUE TITLE
Hi, problems with x99-f8 gaming getting freezes on no undervolting

### ISSUE THREAD

**Issue by JuanjoNuevo** [miyconst/Mi899#30]
I tried your program latest version on huananzhi x99-f8 gaming (DDR4 support, not the T8 version), with xeon 2678v3. Getting some windows freezes using the no undervolt version, so i'm not even trying the undervolted versions. 
Btw, huananzhi has released a bios on the webpage from 2020-8-17. maybe the bios you were using was outdated? I can see a lot more options on the bios, from the new version rather than the outdated version that the motherboard had. The link from the the motherboard download center:
http://www.huananzhi.com/html/1/184/185/427.html

i have used pfptw64.exe to flash the new bios. Is okay, but doesn't get the 3.1ghz all cores turbo unlock cause is an original bios. There is anyw to get the new bios on your program?
I atach my currently working updated bios from the link above downloaded. Thanks in advance for all.
[Huananzhix99NewBiosOriginal2020-8-17.zip](https://github.com/miyconst/Mi899/files/5825289/Huananzhix99NewBiosOriginal2020-8-17.zip)

**Comment by miyconst** [comment]
@JuanjoNuevo could you please specify, which exactly BIOS did you use to get freezes and what is/was the flashing procedure?

I do not have any X99-F8 on my hands to test the latest Huananzhi BIOS, and I don't add untested BIOS options into my app. If someone will produce Turbo Unlocked modifications and test them for me - I will add it to the app.

**Comment by JuanjoNuevo** [comment]
Stock Huananzhi X99-F8 BIOS, TU FFS
Chipsets: X99, C612.
BIOS Settings: Default.
CPU Voltage: Default.
IMC Voltage: Default.
Turbo Unlock Driver: v3_payne_0_0.ffs.
Thats the Bios, i'm getting freezes from your program. Of course, i'm not trying v3_payne_50_50.ffs or v3_payne_70_50.ffs. version or lower, cause 0_0 is getting freezed, more undervolting will get more freezes.

To get your bios working, i selected Stock Huananzhi X99-F8 BIOS, TU FFS (before starting i went to bios and took disabled bios lock) pressed flash bios button (mode selected Flash Programming Tool (FPT)) and runned the flash.bat on a command prompt with admin privileges that i navigated to the temporal folder. then i restarted, and windows getting freezes after 20-30 min. Not cause temps, cause temps are low. i supposed is something with pci-express cause if i take off hdmi, and then insert hdmi on my rx 580, the screen goes full green. is like that pci crashes or something. my graphics cards works perfectly, i used it for a year and bought new, on my old ryzen 5 2600 build.

to flash the bios i passed u, i used the command prompt and did fptw64.exe -f Huananzhix99NewBiosOriginal2020-8-17.rom
(you know before that u need to decompress the rar to get that file).

**Comment by JuanjoNuevo** [comment]
it's supossed that v3_payne gives turbo unlock. so the cpu gets to 3,1-3,3ghz on all cores during long periods of time.

**Comment by JuanjoNuevo** [comment]
Okay, i tried with afudos insteed the Flash Programming Tool (FPT) with your program, everything working now well i think. I passed intel burn test with v3_payne_70_50.ffs after trying v3_payne_0_0.ffs and worked. do not recommend using FPT with your program on those bios. seems like they don't write well or something. afudos is more trusted.

**Comment by miyconst** [comment]
>... then i restarted, and windows getting freezes after 20-30 min.

Could you clarify. After restart, did you go to the BIOS and did you restore the default BIOS settings?

**Comment by JuanjoNuevo** [comment]
Yeah, i restored defaults and then restarted and still getting freezes. Now with afudos all working well

**Comment by miyconst** [comment]
@JuanjoNuevo, you might have got a motherboard with a "rebranded" BIOS chip. Chinese do that every now and then. I have a sample with such a chip and it also gives strange results, some BIOS files can't be written at all, seems like some bits of the chip are dead.

Anyway, thank you very much for sharing the experience with me.
