### ISSUE TITLE
Turbo Boost Unlock Very Unstable with X99-8M-F and E5-2678v3

### ISSUE THREAD

**Issue by parkournerd** [miyconst/Mi899#31]
I'm surprised that this is the first issue posted. Thanks for all your great work. It seems like this must be more of a passion for you than business.

Anyway, I was able to flash the BIOS with RAM timing unlock on this combination, but even the BIOS with Turbo Boost Unlock and no undervoltage was unstable enough that I could not get into Windows without unplugging all accessories and then using TeamViewer. I never experienced this with the stock BIOS or with only RAM timing unlock.

**Comment by parkournerd** [comment]
It seems like I just need to install the EFI driver for the normal voltage / turb boost unlock BIOS and I am currently looking to see if you have a guide for that.

**Comment by parkournerd** [comment]
Couldn't figure it out until now, but it was just because C3/6 were enabled by default in the BIOS flashed. Yay!

**Comment by miyconst** [comment]
Thank you for testing Mi899 and reporting back. Could you please specify which exact BIOS you used? Usually I try to set all necessarily default settings correctly, and the only required thing after flash is "Restore defaults" in the BIOS. Probably I have missed something, since C3/C6 was enabled. By the way, the PEI region injected drivers require C3 state to be enabled for the best configuration.

**Comment by parkournerd** [comment]
Worked with C3 BIOS default:
- hz-x99-8m-f.tp.rom

Windows booting froze until I disabled C3/C6 (forgot by now):
- hz-x99-8m-f.tp.tu.rom
- hz-x99-8m-f.tp.s3tt.5050.rom
- hz-x99-8m-f.tp.s3tt.7050.rom

I tried with C3 enabled as per your link (https://xeon-e5450.ru/socket-2011-3/e5-2600-v3/dobavlyaem-anlok-v-bios-raz-i-navsegda-cherez-s3turbotool/) and that worked.

However, in the process of changing package C State limit and C3/C6 report, my Windows Boot Manager would disappear from the BIOS and simply reverting those parameters did not restore my Windows Boot Manager.

**Comment by miyconst** [comment]
Okay, here how it goes:

- `hz-x99-8m-f.tp.tu.rom` - does not have any drivers in the BIOS, you have to disable C3/C6 and install an EFI driver manually.
- `hz-x99-8m-f.tp.s3tt.5050.rom` - uses an `S3TurboTool` driver, C3 - Enable, C6 - Disable.
- `hz-x99-8m-f.tp.s3tt.7050.rom` - uses an `S3TurboTool` driver, C3 - Enable, C6 - Disable.

Please let me know if you have different experience.

-------

The boot manager is an issue with many Chinese motherboards, it's related to the UEFI boot partition not being detected. You have to either install Windows in legacy mode, rebuild the UEFI partition with the Windows installer, or reinstall Windows.

**Comment by parkournerd** [comment]
- Hz-x99-8m-f.tp.tu.rom worked with C6 Package C State limit and C3/C6 reporting disabled
- Hz-x99-8m-f.tp.s3tt.5050.rom and hz-x99-8m-f.tp.s3tt.7050.rom worked with C2 Package C State limit and C6 reporting disabled

-

I was able to boot back into UEFI mode by setting filtering to UEFI instead of UEFI and Legacy. I do not know if this will last though. It seems sporadic.

I can confirm those C3 - Enable, C6 - Disable work with the undervolted BIOs. hz-x99-8m-f.tp.tu.rom

**Comment by miyconst** [comment]
Then it seems like the issues are solved, at least for now. Closing the issue.
