### ISSUE TITLE
Huananzhi x99 f8

### ISSUE THREAD

**Issue by rashkiller** [miyconst/Mi899#34]
I have an x99 with a 2678v3 and it does not restart, the screen remains black after hitting restart on w10.

**Comment by miyconst** [comment]
@rashkiller could you please specify how the issue is related to Mi899?

**Comment by rashkiller** [comment]
Sorry, maybe not a software specific bug, but it happens to me since I change the BIOS with the Mi899.

**Comment by miyconst** [comment]
Mi899 does nothing with the BIOS or hardware, it's just a collection of BIOS mods and X99  BIOS flashing software.

It could be that your X99-TF is a newer revision, which is not fully compatible with the original BIOS, to be able to say anything more, I need to know which BIOS you used, and have the motherboard on hands for testing.

How long did you wait for the reboot? My X99-TF takes ages to reboot.

**Comment by rashkiller** [comment]
I have X99-F8 and It takes about 1 minute to reboot. 
I used the BIOS from Mi899: Stock Huananzhi X99-F8 TU FFS -70/50mV
Before update, the computer restart normally

**Comment by miyconst** [comment]
Then it behaves as expected. The new Huananzhi BIOS you had before does not have O.C. and RAM timings features, the old one has the features, but boots and reboots very slow, you pick what is important for you.

There is nothing Mi899 can do about it, unfortunately.
