### ISSUE TITLE
Huananzhi X99 F8 TF T8 PEI BIOS too much undervolting

### ISSUE THREAD

**Issue by MG95TUX** [miyconst/Mi899#35]
Hi,
I'm writing this since I noted that, on diverse cases, using PEI BIOS with -70/50 on Xeon 2678v3 on Huananzhi X99 F8, T8 or TF (me and some of my friends went full X99, and everybody got one of those three motherboards, accordingly with what RAM was spare at home / someone likes white boards)  can introduce some instability on the system, expecially if you leave your PC doing high load tasks all nigth (specifically, i'm referring to folding@home project). I also noted that this problems solves itself by flashing your previous BIOS, FFS -50/50, so I'll desume that instability is probably due to excessive undervolting.

Could you please add a -50/50 PEI BIOS for Huananzhi F8/T8/TF on this tool? That would be great, and I'm pretty sure that it would fix those issues.

Thanks in advance, and thanks for your great work

**Comment by miyconst** [comment]
I will do the BIOS mods for you.

**Comment by MG95TUX** [comment]
> 
> 
> I will do the BIOS mods for you.

Thank you, you are great! I will gladly test it as soon as it is ready, and give you feedback, for all three boards!

**Comment by Simoste1969** [comment]
> 
> 
> Hi,
> I'm writing this since I noted that, on diverse cases, using PEI BIOS with -70/50 on Xeon 2678v3 on Huananzhi X99 F8, T8 or TF (me and some of my friends went full X99, and everybody got one of those three motherboards, accordingly with what RAM was spare at home / someone likes white boards) can introduce some instability on the system, expecially if you leave your PC doing high load tasks all nigth (specifically, i'm referring to folding@home project). I also noted that this problems solves itself by flashing your previous BIOS, FFS -50/50, so I'll desume that instability is probably due to excessive undervolting.
> 
> Could you please add a -50/50 PEI BIOS for Huananzhi F8/T8/TF on this tool? That would be great, and I'm pretty sure that it would fix those issues.
> 
> Thanks in advance, and thanks for your great work

same for me

**Comment by Renegade25** [comment]
> Hi,
> I'm writing this since I noted that, on diverse cases, using PEI BIOS with -70/50 on Xeon 2678v3 on Huananzhi X99 F8, T8 or TF (me and some of my friends went full X99, and everybody got one of those three motherboards, accordingly with what RAM was spare at home / someone likes white boards) can introduce some instability on the system, expecially if you leave your PC doing high load tasks all nigth (specifically, i'm referring to folding@home project). I also noted that this problems solves itself by flashing your previous BIOS, FFS -50/50, so I'll desume that instability is probably due to excessive undervolting.
> 
> Could you please add a -50/50 PEI BIOS for Huananzhi F8/T8/TF on this tool? That would be great, and I'm pretty sure that it would fix those issues.
> 
> Thanks in advance, and thanks for your great work

That's the same issue i have

**Comment by MG95TUX** [comment]
Hi, 
I noticed you uploaded PEI -50/50 and -60/50, so I gave them a test first (on a F8), then suggested to my friends and they gave some good feedbacks for TF and T8 too. I (we) can say that those BIOSes work really good, no real bugs, the only thing we noticed is that, on first boot after flashing and resetting to default, already attached USB peripherals on front panel act weird, but once disconnected and reconnected, they work perfectly fine from there on, and this bug does not replicate in any next boot (so no big deal).

Thank you, you're awesome and made mine and our day

MG95Tux

P.S. can't wait to see new version of MI899 with those available by default, tell me if you prefer to keep this issue open till that build or do you prefer to close it anyway, meanwhile enjoy a beer or two, you absolutely deserve them :)

**Comment by miyconst** [comment]
@MG95TUX thank you for testing and the support. I am going to keep the issue open until the next version of Mi899 released.

**Comment by altobalta** [comment]
Hi, same issue here with a Jingsha x99 D8 and Huananzhi X99 F8 Bios -70/50. Can't find the link for the download for -60/50 or -50/50, if someone can tell me would be nice!
Miyconst, do you think is possible to use PEI version with Jingsha D8 motherboard ?
Thanks

**Comment by miyconst** [comment]
@altobalta here is a BIOS you can use - [`huananzhi-x99-f8.s3tt.5050.mi8.rom.zip`](https://github.com/miyconst/Mi899/blob/master/src/Mi899.Data/Bioses/huananzhi-x99-f8.s3tt.5050.mi8.rom.zip), and yes, it's possible to use it with JingSha X99-D8, I do it myself.

**Comment by altobalta** [comment]
Thank you man, is very kind of you. The -60/50 is not stable enough ?

**Comment by MG95TUX** [comment]
> 
> 
> Thank you man, is very kind of you. The -60/50 is not stable enough ?

-60/50 is usually stable, unless you got very unlucky and got a very bad CPU... -50/50 is like safest choice, you could probably lose something versus -60/50 due to hitting power limits sooner, but you're absolutely sure that it works (if you're assembling the PC for yourself, go for -60/50 and give it a go, if you're assembling it for someone who is not into this world, install -50/50 and you'll be sure that it will work whatever the luck in CPU)

**Comment by altobalta** [comment]
Thank you again for this explanation. It is for me, so I'll try the -60/50 first. All the best!

**Comment by andres-skywalker** [comment]
Hello miyconst.
Congratulations on your development. Would you know what is the best bios for Huananzhi f8 v2 + e5 2640v3? I've flashed huananzhi-x99-f8.tu.v3p70.ffs.mi8 and huananzhi-x99-f8.s3tt.7050.mi8.rom, however I noticed a problem when restarting the PC. when restarting the system freezes on the windows login screen. When you turn on the PC everything goes smoothly.

**Comment by MG95TUX** [comment]
> Hello miyconst.
> Congratulations on your development. Would you know what is the best bios for Huananzhi f8 v2 + e5 2640v3? I've flashed huananzhi-x99-f8.tu.v3p70.ffs.mi8 and huananzhi-x99-f8.s3tt.7050.mi8.rom, however I noticed a problem when restarting the PC. when restarting the system freezes on the windows login screen. When you turn on the PC everything goes smoothly.

Follow this message, use pei BIOS to have working sleep mode

> > Thank you man, is very kind of you. The -60/50 is not stable enough ?
> 
> -60/50 is usually stable, unless you got very unlucky and got a very bad CPU... -50/50 is like safest choice, you could probably lose something versus -60/50 due to hitting power limits sooner, but you're absolutely sure that it works (if you're assembling the PC for yourself, go for -60/50 and give it a go, if you're assembling it for someone who is not into this world, install -50/50 and you'll be sure that it will work whatever the luck in CPU)

**Comment by andres-skywalker** [comment]
> 
> 
> > Hello miyconst.
> > Congratulations on your development. Would you know what is the best bios for Huananzhi f8 v2 + e5 2640v3? I've flashed huananzhi-x99-f8.tu.v3p70.ffs.mi8 and huananzhi-x99-f8.s3tt.7050.mi8.rom, however I noticed a problem when restarting the PC. when restarting the system freezes on the windows login screen. When you turn on the PC everything goes smoothly.
> 
> Follow this message, use pei BIOS to have working sleep mode
> 
> > > Thank you man, is very kind of you. The -60/50 is not stable enough ?
> > 
> > 
> > -60/50 is usually stable, unless you got very unlucky and got a very bad CPU... -50/50 is like safest choice, you could probably lose something versus -60/50 due to hitting power limits sooner, but you're absolutely sure that it works (if you're assembling the PC for yourself, go for -60/50 and give it a go, if you're assembling it for someone who is not into this world, install -50/50 and you'll be sure that it will work whatever the luck in CPU)

I tested the -50/50 and -60/50, but unfortunately the problem remains. When restarting the PC the screen freezes on the windows login. It is a small problem because when I do the normal boot without restarting everything works perfectly.

**Comment by miyconst** [comment]
>I tested the -50/50 and -60/50, but unfortunately the problem remains. When restarting the PC the screen freezes on the windows login. It is a small problem because when I do the normal boot without restarting everything works perfectly.

Then it's probably related to the BIOS itself, not to undervolting. Actually, I am getting similar issue with my JingSha X99-D8, but not always, in my case it doesn't matter which BIOS I use though.

**Comment by andres-skywalker** [comment]
> 
> 
> > I tested the -50/50 and -60/50, but unfortunately the problem remains. When restarting the PC the screen freezes on the windows login. It is a small problem because when I do the normal boot without restarting everything works perfectly.
> 
> Then it's probably related to the BIOS itself, not to undervolting. Actually, I am getting similar issue with my JingSha X99-D8, but not always, in my case it doesn't matter which BIOS I use though.

I solved the problem. It really has nothing to do with the undervolt. Believe it is a problem with motherboard drivers. Even the official drivers of huananzhi are incomplete and archaic (I believe that in all Chinese motherboards it is like that). I used a program called Driver Reviver (I activated the option to update beta drivers). After that the boot is incredibly fast (I use a nvme). I just had to be careful because in the driver update I noticed a driver for the nvme controller as if it were from AMD. I accidentally updated this driver and received BSOD at boot. So after a restore point I installed all the available drivers. Except the nvme. Now everything is perfect. Congratulations on your work with Bios. Ps: I noticed that the volume of the beep in the January 2021 bios is slightly lower and smoother.

**Comment by pelostiesos** [comment]
> > > I tested the -50/50 and -60/50, but unfortunately the problem remains. When restarting the PC the screen freezes on the windows login. It is a small problem because when I do the normal boot without restarting everything works perfectly.
> > 
> > 
> > Then it's probably related to the BIOS itself, not to undervolting. Actually, I am getting similar issue with my JingSha X99-D8, but not always, in my case it doesn't matter which BIOS I use though.
> 
> I solved the problem. It really has nothing to do with the undervolt. Believe it is a problem with motherboard drivers. Even the official drivers of huananzhi are incomplete and archaic (I believe that in all Chinese motherboards it is like that). I used a program called Driver Reviver (I activated the option to update beta drivers). After that the boot is incredibly fast (I use a nvme). I just had to be careful because in the driver update I noticed a driver for the nvme controller as if it were from AMD. I accidentally updated this driver and received BSOD at boot. So after a restore point I installed all the available drivers. Except the nvme. Now everything is perfect. Congratulations on your work with Bios. Ps: I noticed that the volume of the beep in the January 2021 bios is slightly lower and smoother.

I was the same issue with my Jingsha X99 D8, but I've resolved it installing the FFS BIOS version with same -90 -50 configuration (for my xeon 2696 v3). At now I've never hav had any freeze when welcome window (W11)
