### ISSUE TITLE
There is no custom bios for the motherboard Huananzhi BD4, ¿Can you make It?

### ISSUE THREAD

**Issue by Daxterciox** [miyconst/Mi899#37]

**Comment by miyconst** [comment]
I have not yet tested this motherboard, thus I can't publish a BIOS for it. The BIOS will be available if I get the motherboard or someone donates me one for testing.

**Comment by speedyb0y** [comment]
With all the tools @miyconst have provide, and all his videos you can actually learn to customize your BIOS.
The first time you do it it's very hard but once you do it becomes very easy.

It's not nice to wait for him to edit and publish custom BIOS for all the motherboards with all the combinations of configurations, overclockings and options available...

the amount of money and time this guy already spent on this tool and his videos is huge

**Comment by speedyb0y** [comment]
@Daxterciox  this is the guide I followed to make my BIOS

I used Google Translate on the page as I don't speak russian.

1) Please save your original BIOS before trying it
2) I used a windows installation just to do it as I don't like to download all those .exe files from unknown sources
I even found a tool to change your boot log lol

https://xeon-e5450.ru/socket-2011-3/e5-2600-v3/dobavlyaem-anlok-v-bios-raz-i-navsegda-cherez-s3turbotool/
