### ISSUE TITLE
Enable 4 gpu on the X99 F8

### ISSUE THREAD

**Issue by lorranmoura** [miyconst/Mi899#39]
Hello @miyconst .

I updated the bios of my x99 f8.

I'm having trouble plugging in several video cards, only allowing 3 gpu. when i add gpu 4 the code d4 appears. and does not let the system start.

how do i connect 4 gpus on f8?

**Comment by miyconst** [comment]
Hi @lorranmoura. Unfortunately, I don't know how to connect 4 GPUs on these motherboards, and I have never tested that. If I will have a chance, I will validate it, but so far I can't really say much.

**Comment by lorranmoura** [comment]
@miyconst  

is there an option to enable above 4g decoding? x99 f8

I didn't find it in the bios.

**Comment by lorranmoura** [comment]
@miyconst note: I am using the motherboard for mining.

**Comment by TerrorrPL** [comment]
> @miyconst note: I am using the motherboard for mining.

Hello, did You find solution for using 4gpu on this motherboard ?

**Comment by SnowFeetus** [comment]
> is there an option to enable above 4g decoding? x99 f8
> I didn't find it in the bios.
 Sorry if Necroing is bad but I just got this working. There is an option for 4G decode, but you must disable all legacy BIOS settings first for it to work. (Stock bios has lots of useless clutter to sift through so it's understandable you missed it, should be in PCIe settings)

**Comment by yamosin** [comment]
> > is there an option to enable above 4g decoding? x99 f8
> > I didn't find it in the bios.
> 
> Sorry if Necroing is bad but I just got this working. There is an option for 4G decode, but you must disable all legacy BIOS settings first for it to work. (Stock bios has lots of useless clutter to sift through so it's understandable you missed it, should be in PCIe settings)

You saved my life ... I've tried by replacing other x99 motherboards, cpu, memory, many ways but spent a week failing and when I was about to give up I inadvertently searched for this and it worked!
Now I can run LLM with x99 using multiple graphics cards in a very cheap way!
