### ISSUE TITLE
error after flashing X99-F8 with Koshak BIOS

### ISSUE THREAD

**Issue by solnyshok** [miyconst/Mi899#40]
I used Mi899 to flash [https://github.com/Koshak1013/HuananzhiX99_BIOS_mods/tree/master/Huananzhi%20X99-F8/2020-05-25%20(%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D1%83%D0%B5%D1%82%D1%81%D1%8F)]. First I chose FPT option, had some errors (sorry, no screenshot, but it flashed several blocks 4 I think, then failed). So I immediately reflashed BIOS with Afuwin option, and it looked all nice, no errors. After reboot, motherboard is stuck at error code bf (or 6f, looks similar), screen is dark, no beeps, after appr 1 min m/b switches off. According to post code table, if this is "bf" it might be "RAM too fast". 

My question is - does it look like a problem that should go away with CMOS reset or I need to order USB CH341A?
I moved JCMOS jumper, removed battery and disconnected m/b from power for about an hour, but it did not help.

**Comment by miyconst** [comment]
It's time to order a CH341A and restore the motherboard BIOS, something went wrong and you have got a corrupted BIOS on the motherboard.

Here you will find basic instructions of how to use CH341A - [CH341a - minimal usage guide, how to read and write a motherboard BIOS](https://www.miyconst.com/Blog/View/2086/ch341a-minimal-usage-guide-how-to-read-and-write-a-motherboard-bios).
