### ISSUE TITLE
Jingsha x99 dual support

### ISSUE THREAD

**Issue by sakurov** [miyconst/Mi899#42]
Hello, @miyconst, are you planning to add Jingsha x99 Dual to you awesome tool? I tried to use your instructions from YouTube and the text version from you web site, but I didn't reach the positive result. I did everything step by step and each step of instruction was successful, but after restart I have no Turbo Boost. Could you help me with this?

**Comment by miyconst** [comment]
Hi @sakurov. I do not add BIOS options to the tool without testing them. If I happen to have a JingSha X99 Dual on my hands again, I will add its support to Mi899.

Most likely you did everything right, but as far as I know, the method I have described is not compatible with dual socket motherboards. You can try this one instead: [Добавляем анлок в биос раз и навсегда через S3TurboTool](https://xeon-e5450.ru/socket-2011-3/e5-2600-v3/dobavlyaem-anlok-v-bios-raz-i-navsegda-cherez-s3turbotool/).

**Comment by sakurov** [comment]
Thank you for advice! I reached the successful result with that instruction. I think that my problem was in Bios version, I had a 04.14.2020, and yesterday I flashed 01.08.2020, I got some troubles with boot options, but I solved them by linux live cd. After that I got Unlock.
