### ISSUE TITLE
Problem adding RAM to Huananzhi X99-F8

### ISSUE THREAD

**Issue by Yavahel** [miyconst/Mi899#44]
Hi,

This is not an issue related to your BIOS mod but maybe you can help me.
I have installed 4 8GB ECC DIMMs on my X99-F8 and had no problems.
After that i bought 4 more DIMMs (same shop) and I replaced the old ones in order to test its funcionality and everything ok.
The problem is when I try to install all 8 DIMMs.
First I had 4 DIMMs (in the 4 slots together) and I put the other 4 in the free slots.
When I try tu power-on my PC I have code 67 when starting the BIOS.
I flashed the BIOS with your optimized one but same issue.
Can you help me with it? I think maybe any slot is broken or something but i hope it's a jumper config related or any param in the BIOS ....

**Comment by miyconst** [comment]
Please do not use this repository to ask Mi899 unrelated questions. Closing the issue, but feel free to contact me on Instagram or Discord, if you need any help.
