### ISSUE TITLE
Uefi boot barely works on JingSha X99M-H2

### ISSUE THREAD

**Issue by fish7221** [miyconst/Mi899#45]
I've flashed the JingSha X99M-H2 motherboard with "X99M-G2 Miyconst optimal" and also tried the "TU FFS -50/50mv", But on both bioses my 970 evo nvme 1TB boot drive wasn't detected as UEFI drive so there was no windows boot manager to boot from.
Rarely it detected the drive correctly and booted via windows boot manager mode (After resetting bios to defaults many times and rebooting the system about 20 times, and then on the next boot it didn't recognise the drive correctly again).
I tried enabling/disabling CSM and then when CSM enabled -  tried UEFI only - But no go.
Finally booted via winPE (Strelec) and flashed it to original dumped bios and now UEFI works consistently.
The tried bioses seems to have some UEFI implementation bug.

**Comment by miyconst** [comment]
This is a known issue of many Chinese X99 motherboards. Unfortunately, there is nothing I can do about it. If you are interested to get a better BIOS without this issue, you can contact [BIOS-iEngineer](https://github.com/BIOS-iEngineer).

If you want to just resolve the current issue, you have a few options:

- Install Windows in CSM mode.
- Try to restore the UEFI partition with the Windows Installation media.
- Reinstall Windows after applying Turbo Boost Unlock.

Or perform the following steps, which may or may not help:

- Power off the PC.
- Disconnect all storage devices.
- Clear CMOS.
- Boot into BIOS and restore defaults.
- Save changes and reset.
- Power off the PC.
- Connect back the storage devices.
- Power on the PC.
- It this stage the system *should* recognize the UEFI partition and boot properly, but it's not guaranteed.

**Comment by fish7221** [comment]
Thank you very much for the detailed info.
