### ISSUE TITLE
X99 RS9 2630 V3 Freezes Randomly

### ISSUE THREAD

**Issue by Ecabmad** [miyconst/Mi899#47]
It's an B85 Chipset, i flashed x99 8MF -50/-50 Bios and everything was right but then it suddenly freeze, even during idle, sometimes 20 seconds after booting (even during the Windows startup screen) and sometimes 15 min while in the desktop for no reason, the specs of the system are an Nvidia 6600GT (temporary) and 4*4GB DDR4 ECC and a Crucial MX500.

In the Bios i can navigate without any issue.

**Comment by miyconst** [comment]
Did you restore the BIOS defaults after flashing the modded BIOS? Does the system work 100% stable with the original BIOS?

**Comment by Ecabmad** [comment]
I have the original BIOS as a *.bin file, can I flash, it from the BIOS itself without an OS?

**Comment by miyconst** [comment]
>I have the original BIOS as a *.bin file, can I flash, it from the BIOS itself without an OS?

No, but you can flash it using an MS-DOS bootable USB drive.

**Comment by Ecabmad** [comment]
the one from mi899 Q87 would work on the B85?

**Comment by miyconst** [comment]
>the one from mi899 Q87 would work on the B85?

Yes, it should be, but I can't guarantee.
