### ISSUE TITLE
undervolting w/o turboboost unlock (for v4 cpu)

### ISSUE THREAD

**Issue by lmspw** [miyconst/Mi899#49]
Hi, is it possible to do undervolting for my machinist rs9 without turboboost unlock to use v4cpu?

**Comment by miyconst** [comment]
Hi there. I have not tried it myself, but this tool claims to have such a possibility - [Добавляем анлок в биос раз и навсегда через S3TurboTool](https://xeon-e5450.ru/socket-2011-3/e5-2600-v3/dobavlyaem-anlok-v-bios-raz-i-navsegda-cherez-s3turbotool/).
