### ISSUE TITLE
Please Help ZX-99EV3_V1.31 KLX99109

### ISSUE THREAD

**Issue by krisia06** [miyconst/Mi899#51]
Hi. Thank You for your informative Youtube Channel.
I bought a generic X99 board with label above on box.
The board looks like Panshi X99-D4. Windows shows C610 chipset.

The firmware I saved with your program has ID: KLX99109.
Two issues I'm having are Linux cannot enable ECC.
(I purchased 1Rx4 8GB ECC ram kit for it) prime95 passes fine.
Do Not see any options in BIOS to enable ECC.

And USB 3.0 performance is bad. less than 70MB/sec.
Is there a BIOS you would recommend that might fix these issues?
Thank You.  KH

**Comment by miyconst** [comment]
Hi. The following two videos answer your questions:

- https://youtu.be/QwJil2AsJnU
- https://youtu.be/HozIT2X-cKk
