### ISSUE TITLE
Kllisre x99 b5 support

### ISSUE THREAD

**Issue by plancha2002** [miyconst/Mi899#52]
Hi, I just bought a kllisre x99 b5 and I want to do the turbo hack. I noticed that even Mi899 still does not have support for it, but in forums in vk I saw that there are people who have made bios for this. My fear is that I do not know to what extent this is reliable and I am waiting for it to be added to the program. Thank you very much and happy holidays.
Pd: sorry for the English this is translated by google :)

**Comment by miyconst** [comment]
So far I do not plan to test X99-B5 as it seems to be exactly the same as X99-RS9 / X99 V201 / X99S-2011 / X99-H9 and other boards from this range, but if I get a chance, I will validate X99-B5 as well.

**Comment by plancha2002** [comment]
oh, thanks :)

**Comment by hendrik21** [comment]
hi! I bought the same motherboard and I see this issue is still open, I'm still waiting to get a power supply, so I can't check at the moment if this model appears in the database. @plancha2002 have you checked if this board is compatible with some of the previously mentioned?

**Comment by Rambit41** [comment]
Hi, I have a Kllisre x99-B5 v1.1 motherboard. My BIOS file, which includes active hidden menus, Turbo Unlocking and Resizable Bar features, is attached. Undervolting was not applied in BIOS. The processor operates at standard voltage.
[X99B5V1.1.zip](https://github.com/miyconst/Mi899/files/14577218/X99B5V1.1.zip)
