### ISSUE TITLE
Machinist X99-RS9 + E5 2673 V3 - which Bios?

### ISSUE THREAD

**Issue by KredensKuchenny** [miyconst/Mi899#53]
Hi, which Bios will be good for Machinist X99-RS9 + E5 2673 V3 to make turbo unlock?
EDIT. 
This is newest revision of this mobo (with LED screen debuger)

**Comment by miyconst** [comment]
As far as I know, the new revision of X99-RS9 is still compatible with Huananzhi X99-8M-F BIOS, and this is what I would recommend. Undervolting level is individual per each CPU, but -70/50mv should be a safe start. Nevertheless, I think it's a very bad idea to run E5-2678 V3 on X99-RS9, especially with Turbo Boost Unlock.

**Comment by KredensKuchenny** [comment]
So after flashing windows sometimes freeze on web browser / other programs... When i improve airflow i will try -60/50 (if exist) or -50/50 mV

**Comment by miyconst** [comment]
Did you do the following after flashing a new BIOS?

- Power off PC.
- Clear CMOS.
- Power on PC.
- Go into the BIOS.
- Restore defaults.
- Save and reset.

**Comment by KredensKuchenny** [comment]
No, after flashing a new BIOS I restore defaults only, but the issue is similar to https://github.com/miyconst/Mi899/issues/35
and exsist only when debug LED screen shows 73, when i see AA (after reboot) everything is good https://github.com/miyconst/Mi899/issues/38
73 error exist every time (on default BIOS too) but after reboot gone and change to AA

**Comment by miyconst** [comment]
>... on default BIOS too

In this case the issue is not related to Turbo Boost Unlock and you need to isolate the problem. Most likely the motherboard is not functioning well.

**Comment by KredensKuchenny** [comment]
Ok, i find problem which provoke 73 error. Switching fast boot on windows to off resolve issue with 73 error code. After that, new bios with UV + TU works good

**Comment by miyconst** [comment]
>Switching fast boot on windows to off resolve issue with 73 error code.

Thank you for the info!
