### ISSUE TITLE
Bios Recommendation

### ISSUE THREAD

**Issue by Billy1337** [miyconst/Mi899#54]
Hi there, 

First off thanks for your hard work in creating the fixes and constant support for these chinese motherboards.
I have recently purchased a Machinist - X99 - RS9, now I have watched your video where you reviewed and mentioned you flashed the bios to fix USB 3 Issues, The cpu I have is the Xeon E5-2530 v3 and I have downloaded your software to flash the motherboard, upon discovering there is about 11 Bios's to choose. What one would you recommend personally? I'm just looking for a stable build. 
Sorry I didnt know where else to contact you.

Regards from Australia.

**Comment by miyconst** [comment]
Hi @Billy1337.

I assume that you have got Xeon **E5-2630 V3** and not E5-2530 V3. In this case I would go with Huananzhi X99-8M-F BIOS with Turbo Boost Unlock using PEI method and -70/50mv undervolting.

This BIOS: [`huananzhi-x99-8m-f.tp.s3tt.7050.rom.zip`](https://github.com/miyconst/Mi899/blob/master/src/Mi899.Data/Bioses/huananzhi-x99-8m-f.tp.s3tt.7050.rom.zip).
