### ISSUE TITLE
any good Bios for ZX-DU99D4 

### ISSUE THREAD

**Issue by nmocruz** [miyconst/Mi899#55]
Hi, good bios for ZX-DU99D4? I dont need really the turbo boost. I wondering if any bios update/driver can solve the sleep mode problem. I can enable it on the bios but it has problems to awake up again.

**Comment by miyconst** [comment]
I am sorry to say, but I don't have any better BIOS options for this motherboard, moreover, as far as I know, this is a hardware not software limitation.

**Comment by nmocruz** [comment]
Ok, what BiOS exists for this model and what kind of improvements can be made beside the turbo.
