### ISSUE TITLE
Machinist RS9 does'nt boot from m.2 nvme

### ISSUE THREAD

**Issue by Lucho20101** [miyconst/Mi899#56]
Hi, I got a Machinist RS9, after updating the original BIOS to -50/-50 mV version, the system won't boot from nvme, so I have to go to BIOS and restore factory defaults or clear CMOS and then the system boots normally from nvme, but it only happens the first time, after rebooting again, the system doesn't find a boot medium.
Is there any suggest?

**Comment by miyconst** [comment]
Hi, this question is not related to Mi899, but this is how you fix it:

1. Shut down the computer.
2. Disconnect the power cord.
3. Disconnect all storage devices.
4. Turn on the computer.
5. Go to the BIOS and restore defaults.
6. Save changes and restart.
7. Go to the BIOS and apply any extra settings you wish, such as RAM timings. This is an optional step.
8. Turn off the computer and disconnect the power cord.
9. Connect all storage devices back.
10. Turn on the computer, it should work properly.
