### ISSUE TITLE
BIOS incompatibility?

### ISSUE THREAD

**Issue by bchan009** [miyconst/Mi899#57]
I am not sure why, but it seems like my Machinist X99-G7 is NOT compatible with Huananzhi X99-8M-F BIOS.

1) I flashed Huananzhi X99-8M-F TU 50-50 BIOS using Mi899, but got permanent black screen (bricked?) on boot.
2) I flashed stock Machinist X99-G7 BIOS with CH341a, everything working again.
3) I flashed Huananzhi X99-8M-F stock BIOS / TU 50-50 BIOS with CH341a, and both get black screen.
4) I flashed Huananzhi **_X99-8M-T_** stock BIOS from Huananzhi site with CH341a, and it is working.

So it seems like some Machinist X99-G7 require 8M-**_T_** BIOS?  I wonder if it is a new board revision...sadly it looks like there is no 8M-T TU BIOS, so I will have to run stock CPU settings for now.

Just wanted to share my results. Maybe this will be helpful for other Machinist X99-G7 owners.

Maybe you can add this information to Mi899 or add a note to your X99-G7 video?

System specs:
CPU: E5-2673v3
RAM: 128GB Samsung DDR3 ECC (4 x 32GB PC3-14900L)

**Comment by bchan009** [comment]
I have done some more testing and even the Huananzhi X99-8M-T BIOS is not working 100% properly.

When using the X99-8M-T BIOS the system boots and runs properly, but it cannot do a full shut down.  Choosing 'Shut Down' in Windows leaves the motherboard still powered on.

I have reverted to the stock X99-G7 BIOS for now.  It seems like my particular board is not compatible with other BIOS files.

**Comment by miyconst** [comment]
@bchan009 could you please check what is your motherboard chipset? Also it would be helpful if you could post detailed pictures of the motherboard.

Is there any chance you could check if the first PCI-E X1 slot works?

**Comment by bchan009** [comment]
@miyconst 

Chipset is C226.  I will post some pictures when I have time this weekend.

**Comment by bchan009** [comment]
> @bchan009 could you please check what is your motherboard chipset? Also it would be helpful if you could post detailed pictures of the motherboard.
> 
> Is there any chance you could check if the first PCI-E X1 slot works?

Here are some photos of my motherboard.  It doesn't seem to be any different from the others I have seen online.  Sadly I have no way to test the first PCI-E X1 slot.

I can't find any information about this BIOS chip online.  Might be a Chinese clone - flashing it as W25Q128FV seems to work.

![20220210_000326](https://user-images.githubusercontent.com/35556639/155217150-d14e4e70-e119-4a17-a772-9d8522cb9853.jpg)
![20220221_182520](https://user-images.githubusercontent.com/35556639/155217153-30b01d28-9efd-48ce-9d6e-5b4bf9d2b31a.jpg)
![20220221_182534](https://user-images.githubusercontent.com/35556639/155217154-5eccb4f2-52ce-4f32-87a0-4ec802d0edb3.jpg)
![20220221_182556](https://user-images.githubusercontent.com/35556639/155217156-63a9b441-13fb-494b-9d2d-0b027e6c3ec3.jpg)
![20220221_182634](https://user-images.githubusercontent.com/35556639/155217157-ac7dfd36-2728-4cad-b461-fec3a2492eb0.jpg)
![20220221_182644](https://user-images.githubusercontent.com/35556639/155217159-946e7d5a-3871-4411-8fc1-fa84a63f5153.jpg)

**Comment by mdemario13** [comment]
How can I go back to the stock Machinist bios?

**Comment by miyconst** [comment]
>How can I go back to the stock Machinist bios?

You can flash the original BIOS the same way you flash modded version.
