### ISSUE TITLE
Huananzhi X99-T8 (new revision) compatibility

### ISSUE THREAD

**Issue by wpyoga** [miyconst/Mi899#59]
Hello, and first of all thank you for the great tool and great selection of BIOS images. I have the new revision of Huananzhi X99-T8, with a Xeon E5-2696v3.

I tried flashing [huananzhi-x99-f8.tu.v3p50.ffs.mi8.rom.zip](https://github.com/miyconst/Mi899/blob/master/src/Mi899.Data/Bioses/huananzhi-x99-f8.tu.v3p50.ffs.mi8.rom.zip) and then [huananzhi-x99-f8.s3tt.5050.mi8.rom.zip](https://github.com/miyconst/Mi899/blob/master/src/Mi899.Data/Bioses/huananzhi-x99-f8.s3tt.5050.mi8.rom.zip). Both BIOS images have a common problem: on every start-up (after a shutdown or a restart), the motherboard beeps 4x (all short beeps), and goes into the BIOS settings instead of booting into the OS. I can boot into the OS from the Boot Override menu option.

With stock BIOS, CPU-Z benchmark gives 68xx points (multi thread). I don't remember the performance of the TU version, but the S3TT version gives 79xx points.

Then I used UPT to patch and flash the S3TT BIOS image. It states that a boot-to-recovery problem is detected and fixed. Sure enough, after flashing, I can boot directly into the OS, and the motherboard does not beep 4x anymore.

Is the BIOS error an expected behaviour, especially with the new revision boards? In that case, won't it be helpful if we patch all the BIOS images using UPT, for the new revision of X99-T8? I can help do this, but this is actually very trivial to do (just use UPT to patch each BIOS image) once we have figured out what the problem is...

**Comment by wpyoga** [comment]
I tried to find the optimal undervolt values using ThrottleStop. However, after I set an undervolt value, when I ran the CPU-Z benchmark again, the score will be lower at 68xx. During this time, I notice that the CPU multiplier is 28x. This persists until I reboot the machine, after which the CPU-Z score becomes 79xx again, and the CPU multiplier is 32x instead. Is there a better way to find the optimal undervolt value?

I also noticed that on the Windows desktop, the idle power consumption is a bit high using this BIOS:
- [huananzhi-x99-f8.s3tt.5050.mi8.rom.zip](https://github.com/miyconst/Mi899/blob/master/src/Mi899.Data/Bioses/huananzhi-x99-f8.s3tt.5050.mi8.rom.zip) ~ 90 W
- [HNX99T8_200525_kot.zip](https://github.com/Koshak1013/HuananzhiX99_BIOS_mods/blob/master/Huananzhi%20X99-T8/2020-05-25%20(%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D1%83%D0%B5%D1%82%D1%81%D1%8F)/HNX99T8_200525_kot.zip) ~ 80 W

The kot BIOS image results in a lower CPU-Z score of 75xx (CPU multiplier is 30x). I used UEFITools to extract the ser8989_S3TurboHack.ffs module from your S3TT image and integrated it into the kot image, but it still gets a 30x CPU multiplier when running CPU-Z benchmark. Are there any BIOS settings that makes the CPU multiplier go higher when using the S3TT image?

**Comment by miyconst** [comment]
Hi.

The latest revision of Huananzhi X99-TF/F8/T8 motherboards is not compatible with the original BIOS.

You can try this BIOS:
https://github.com/BIOS-iEngineer/HUANANZHI-X99-F8-2021

I am working on the X99 status update video, but for now you have to implement Turbo Boost Unlock yourself.

**Comment by wpyoga** [comment]
I'm trying to avoid using the CH341A programmer. Oh well, I'm looking forward to your video. Thanks!
