### ISSUE TITLE
Kllisre and Bios

### ISSUE THREAD

**Issue by HaYaToSkAn** [miyconst/Mi899#60]
Hello Genius of Chinese boards
I have some doubts to see if you can solve them
I have a Kllisre X99 V201 with an NVME M2 disk, I think that to flash the Bios I should use the huananzhi-x99-8m-f.tp.s3tt.5050 ?
Can I have any windows boot problem having a NVME M2 drive after flashing?
In case windows does not start, is there any solution, installing the factory bios or some other solution?
I've never done a Bios flash and I'm afraid of bricking the board and not knowing what to do.
Thanks for everything, keep up the great work and contribution you give to the community!!!

PS: sorry for my english, I'm using a translator

**Comment by miyconst** [comment]
@HaYaToSkAn hello.

Here are some answers, I hope it help.

1. **Do not touch the BIOS if you are afraid**.
2. Study the subject well and flash the BIOS only if you understand what you are doing.
3. Study the subject well and learn the difference between different BIOS mods. Pick the one that fits your motherboard & CPU.
4. If you system is installed in UEFI mode and fails to boot after a BIOS flash, use these steps to get it fixed - [Machinist RS9 does'nt boot from m.2 nvme #56](https://github.com/miyconst/Mi899/issues/56).
