### ISSUE TITLE
Machinist k9 v2.0

### ISSUE THREAD

**Issue by jonnyloureiro** [miyconst/Mi899#61]
Hi dude!

I just got my machinist k9 v2 board and xeon e5-2650 v3, I'm super excited, have you done any version of turboboost unlocking and memory timings for this version? in your software you only have version 1.0. can you help me? I was thinking 50/50. what do you think?

best regards from your brazilian admirer. @miyconst

**Comment by miyconst** [comment]
@jonnyloureiro this video has answers to all of your questions - [🇬🇧 PC with Machinist X99-K9 V2.0 and i7-5820k – BIOS, overclocking, tuning, review, and impressions](https://youtu.be/FhnGfcYrJRQ).

**Comment by jonnyloureiro** [comment]
Tanks!
