### ISSUE TITLE
BSOD after bios update. RS9-100/-50

### ISSUE THREAD

**Issue by mondi31** [miyconst/Mi899#62]
Hello,

Just updated my RS9's bios using mi899 and when I rebooted I am constantly being greeted by bsod. How can i revert to default bios. Please help. Thanks.

**Comment by miyconst** [comment]
This video answers your question: [🇬🇧 How to restore your X99 Turbo-Unlocked system if it locks | Miyconst Answers 05](https://youtu.be/r2CXlt_qKVk).
