### ISSUE TITLE
Unhandled exception has occurred

### ISSUE THREAD

**Issue by MagnoAlberto** [miyconst/Mi899#64]
I have a MACHINIST X99-MR9D PLUS with Xeon CPU E5-2670 v3 @ 2.30GHz, 2295 Mhz, and after opening the tool and performing a search to locate my mothercard, I get an "Unhandled exception", see below.

Unhandled exception has occurred in your application. If you 
click Continue, the application will ignore this error and attempt 
to continue. If you click Quit, the application will close 
immediately. 
Object reference not set to an instance of an object. 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mi899.MotherboardsPartialForm.<>c__DisplayClass10_0.<PopulateDataSource>b__1(MotherboardRowData x) in F:\GitHub\Miyconst\Mi899\src\Mi899\MotherboardsPartialForm.cs:line 135
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Mi899.GenericBindingList`1..ctor(IEnumerable`1 source) in F:\GitHub\Miyconst\Mi899\src\Mi899\GenericBindingList.cs:line 35
   at Mi899.MotherboardsPartialForm.PopulateDataSource() in F:\GitHub\Miyconst\Mi899\src\Mi899\MotherboardsPartialForm.cs:line 141
   at Mi899.MotherboardsPartialForm.txtSearch_KeyPress(Object sender, KeyPressEventArgs e) in F:\GitHub\Miyconst\Mi899\src\Mi899\MotherboardsPartialForm.cs:line 161
   at System.Windows.Forms.Control.OnKeyPress(KeyPressEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.22.11601
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Private.CoreLib.dll
----------------------------------------
Mi899
    Assembly Version: 1.2.7.0
    Win32 Version: 1.2.7.0
    CodeBase: file:///C:/temp/Mi899-1.2.7/Mi899.dll
----------------------------------------
System.Runtime
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Runtime.dll
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly Version: 3.1.8.0
    Win32 Version: 3.100.820.42004
    CodeBase: file:///C:/temp/Mi899-1.2.7/Microsoft.Extensions.DependencyInjection.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.ComponentModel.dll
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly Version: 3.1.8.0
    Win32 Version: 3.100.820.42004
    CodeBase: file:///C:/temp/Mi899-1.2.7/Microsoft.Extensions.DependencyInjection.Abstractions.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/netstandard.dll
----------------------------------------
Mi899.Data
    Assembly Version: 1.2.7.0
    Win32 Version: 1.2.7.0
    CodeBase: file:///C:/temp/Mi899-1.2.7/Mi899.Data.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.122.10304
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.ComponentModel.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Collections.Specialized.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Runtime.InteropServices.dll
----------------------------------------
System.Collections
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Collections.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.IO.FileSystem.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Runtime.Extensions.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/temp/Mi899-1.2.7/Newtonsoft.Json.dll
----------------------------------------
System.Memory
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Memory.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 4.0.15.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Collections.Concurrent.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Runtime.Numerics.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 4.0.6.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Private.Uri.dll
----------------------------------------
System.Linq
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Linq.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.ObjectModel.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Private.Xml.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Reflection.Emit.Lightweight.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.700.22.11601
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Private.CoreLib.dll
----------------------------------------
System.Threading
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Threading.dll
----------------------------------------
System.Resources.ResourceManager
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Resources.ResourceManager.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 4.0.2.3
    Win32 Version: 4.700.21.51508
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.Debug
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Diagnostics.Debug.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Diagnostics.Tracing.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Threading.Thread.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.122.10304
    CodeBase: file:///C:/temp/Mi899-1.2.7/Accessibility.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///C:/temp/Mi899-1.2.7/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Buffers
    Assembly Version: 4.0.5.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Buffers.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Collections.NonGeneric.dll
----------------------------------------
System.Windows.Extensions
    Assembly Version: 4.0.1.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Windows.Extensions.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 4.0.1.0
    Win32 Version: 4.700.20.21406
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Resources.Extensions.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 4.0.3.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Net.WebClient.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 4.3.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Text.Encoding.Extensions.dll
----------------------------------------
CommonMark
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
    CodeBase: file:///C:/temp/Mi899-1.2.7/CommonMark.dll
----------------------------------------
System.IO
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.IO.dll
----------------------------------------
System.Globalization
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Globalization.dll
----------------------------------------
System.Text.Encoding
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Text.Encoding.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 1.4.5.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 1.2.5.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.Collections.Immutable.dll
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.22.12208
    CodeBase: file:///C:/temp/Mi899-1.2.7/System.IO.MemoryMappedFiles.dll
----------------------------------------

************** JIT Debugging **************

**Comment by miyconst** [comment]
Thank you for the report, the issue will be fixed in the next release.

**Comment by miyconst** [comment]
Fixed in the `1.2.8` release.
