### ISSUE TITLE
Support for Machinist X99 MR9S & MR9D

### ISSUE THREAD

**Issue by BeheldX** [miyconst/Mi899#65]
Hey, I just wanted to ask if you plan to add support/already have support for the Machinist X99 MR9S and MR9D (and the Plus variants)? Or if one of the Huananzhi or other bioses work with them? They must be fairly new as I’ve scoured your channel and watched the longer video showcasing lots of the Chinese boards, and haven’t seen much about them. I know you already have support for the MR9A, and I’ve looked through your files/code but haven’t seen these specifically mentioned. Maybe these are basically the same as the MR9A? I know the MR9D supposedly uses an actual X99 chip though rather than the B85.
   Anyways, I’ve just been looking at possibly getting one of these and wanted to make sure I’ll be able to use a custom BIOS on them.
   As a side question, would you even recommend these at all? I saw your review on the MR9A and it seemed to have pretty impressive quality that sort of surprised you. Thanks for all your hard work!

**Comment by miyconst** [comment]
Machinist X99-MR9D has arrived to me about a month ago, here is an unboxing video: [Unboxing Machinist X99-MR9D](https://m.youtube.com/watch?v=3VJPngQMouM), I plan to test it soon.

Can't say much about the rest of the motherboards before I test them.

My Huananzhi X99-TF-Q review is going to be live soon.

**Comment by alexnetdoc** [comment]
Guys, have you checked if MR9D and MR9D-Plus have IOMMU options enabled?  I am very much interested to use this board as a server with Proxmox and virtualize Truenas, but if PCIe cannot be passthrough to the VM, then this board is useless even with server X99 chipset
