### ISSUE TITLE
Atermiter X99H support ?

### ISSUE THREAD

**Issue by kriss6557** [miyconst/Mi899#67]
Hi @miyconst,
I just installed an Atermiter X99H v1.31 running BIOS version X99HA00E, with a Xeon E5-1650v3.
It looks like your utility doesn't cover this configuration.
Do you think there is chance you could support it, and don't know if my Xeon can run with lower voltage.

BTW, the Atermiter store on Aliexpress provided me the link to the latest BIOS update:
https://cowtransfer.com/s/1150fd266f6c44 点击链接查看 [ X99HA009小板4通道KN85小版BIOS.rar ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 vh5uae 查看；

**Comment by miyconst** [comment]
Could you please paste a picture of the motherboard or link the AliExpress page. Atermiter is not a motherboard manufacturer, it's an AliExpress store name.

**Comment by kriss6557** [comment]
Here it is:
https://fr.aliexpress.com/item/1005003035860635.html?algo_exp_id=afae8a80-e6f8-43eb-8157-1155c662ad99-1&pdp_ext_f=%7B%22sku_id%22%3A%2212000023366953330%22%7D

BTW the BIOS link is and old version, older then the one installed on the board (X99HA00F)

**Comment by miyconst** [comment]
I am sorry to say, but this motherboard won't get any support from me. These videos explain why:

- [🇬🇧 ZX_99EV3, ZX_MINX9D4, ZX_DU99D4, ZX_99D3A4 – please do not buy these motherboards](https://youtu.be/7Pyef_ySHwo).
- [🇬🇧 Review of Trash X99 (Kllisre, Machinist) LGA 2011-3 | E5-2620 V3 | Turbo Unlock | GTX 1660](https://youtu.be/mZHcdbmxI3s).
