### ISSUE TITLE
Jginyue X99 D8 comos jumper

### ISSUE THREAD

**Issue by 3Dickulus** [miyconst/Mi899#68]
The Jginyue X99 D8 motherboard has a cmos clear jumper but it doesn't have a header soldered in place. It seems to work though.

The header that is right next to the clear cmos jumper is the "Auto On" jumper. This jumper bypasses the front case switch relay and allows PSU switch to determine ON or OFF state. So if the PSU power switch is ON then it will power up and boot after a power failure. In the default position (shown) it is set to engage the relay from the front case power switch.
![JGINYUE-X99-D8-CMOS-CLEAR](https://user-images.githubusercontent.com/4978723/185266797-39a7ecc0-dc69-4429-9b07-17a331433400.JPG)

**Comment by miyconst** [comment]
Thank you for the info!
