### ISSUE TITLE
Booting always to BIOS after BIOS Update

### ISSUE THREAD

**Issue by seakrebel** [miyconst/Mi899#69]
I have a new Huananzhi X99-F8 which was working just fine, but I wanted to unlock more BIOS options and of course enable Turbo Boost. 
After flashing TU FFS (tried -70/50mv, and 0/0), and tried using both flash tools, my PC is always booting automatically in BIOS.
Also tried resetting CMOS battery, as well as loading default config in BIOS, but it did not help.

Booting into Windows is still possible after manually selecting "Boot Override" inside BIOS. It just doesn't want to boot automatically.

I already checked SATA settings, and actually disabled all SATA controllers because I am using NVMe anyway.
Also I disabled CSM support because I don't use Legacy boot anyway. 

Not forget to mention, I'm getting four beeps after starting PC, and shortly an error "F9" on the digital display on motherboard itself, but right after it goes into BIOS and motherboard shows "AA" as it booted correctly.
This error was also not present before BIOS update.

**Comment by miyconst** [comment]
The BIOS in Mi899 is from / for the first revision from of X99-F8, I am not sure if it's compatible with your motherboard.

I can suggest you to look at these BIOS options:

- [BIOS-iEngineer / HUANANZHI-X99-F8](https://github.com/BIOS-iEngineer/HUANANZHI-X99-F8).
- [BIOS-iEngineer / HUANANZHI-X99-F8-2021](https://github.com/BIOS-iEngineer/HUANANZHI-X99-F8-2021).

For the UEFI partition bug you can the following steps: https://github.com/miyconst/Mi899/issues/56#issuecomment-1026149828
