### ISSUE TITLE
HUANANZHI X99 F8

### ISSUE THREAD

**Issue by korichou** [miyconst/Mi899#70]
Bonjour j'ai cette carte mère HUANANZHI X99 F8 qui fonctionne avec un Xeon 2697 v3 mais je ne dépasse pas 3100 GHz
Quel bios faut-il que j'utilise pour augmenter sa fréquence ?
Merci d'avance et bonne journée.

**Comment by miyconst** [comment]
This video has the answers and explanations: [🇬🇧 LGA 2011-3 (X99) platform overview and status update in 2022 Q3](https://youtu.be/AW0QgQNbBwA).
