### ISSUE TITLE
I cannot open the image files to see them big enough when I click on the motherboard images

### ISSUE THREAD

**Issue by slobele** [miyconst/Mi899#71]
I think it looks like the reason is mixing linux like path separator with windows like, maybe you could prefix them with file://and place the path only "/" separated ? BTW I haven't read the source code I'm just guessing

**Comment by miyconst** [comment]
Please specify what is your OS and what means "cannot"? Do you get an exception or nothing happens?

**Comment by slobele** [comment]
yes, I have Windows, the exception is more or less that the file does not
exist and I think it is because it mixes / with back / in the file path. in
Windows paths such like file://path usin only / can work I think, maybe it
could be a possible solution ?

**Comment by slobele** [comment]
BTW, thank you very much, it is a great work you do there

**Comment by miyconst** [comment]
>Windows paths such like file://path usin only / can work I think, maybe it could be a possible solution ?

I need some more info about the issue. Please attach some screenshots of what's going on and what kind of error you are getting.
