### ISSUE TITLE
Jingsha X99 D8i mainboard

### ISSUE THREAD

**Issue by Ant-Bugworks** [miyconst/Mi899#72]
Hi, 
First of all, TOP WORK, you are doing a great things for the community! 
i just got a new Jingsha X99 D8i mainboard and wanted to unlock the turbo but im am not sure if it is compatible with one of the already implemented bios.  Chipset is a x99 C612 
Can it be implemented? should i provide any further infos? I included the original bios, maybe it helps
Cheers
Ant
[X99-D8I.zip](https://github.com/miyconst/Mi899/files/10034252/X99-D8I.zip)

**Comment by miyconst** [comment]
Hi there. Please join my Discord if you need help with Turbo Boost Unlock, I do not modify BIOS for motherboards that I have not tested myself.
