### ISSUE TITLE
X99 RS9 with b85 chipset and E52640V3 and I get random screen freezes. Which BIOS?

### ISSUE THREAD

**Issue by Deifuss** [miyconst/Mi899#73]
Hi all,

It is my first post here. First of all, thank you for your time creating solutions an tools to improve our motherboards.
I have recently get a **Machinist X99 RS9** with:

**- Xeon E5 2640 V3**
**- B85 chipset** 
- 2*8G DDR4 ECC RAM 2133Mhz
- SSD NVMe 512GB
- PSU 650W
- GPU Geforce GTX 4GB

My problem is that I get random screen freezes (sometimes just start, sometimes after minutes or hours...) where keyboard and mouse do not respond but fans still running, and I've to hold down the power button to restart the system. It has also happened to me during the Windows installation process! I have a slight suspicion that it usually occurs in I/O operations to SSD.

Now I'm thinking of flash the BIOS with your mi899 application, and I would like to ask you what BIOS would you recommend to get a more stable system.

Thak you very much in advance!
![Placa base X99 RS9](https://user-images.githubusercontent.com/120734198/208161467-41c40268-51d6-4ab9-9ddf-cbfee7c8c2b0.png)

**Comment by miyconst** [comment]
>My problem is that I get random screen freezes

- What BIOS do you use?
- Is the Turbo-Boost Unlock in place?
- Did you apply any undervolting?
- Did you test your RAM with Memtest86?

**Comment by Deifuss** [comment]
Thanks for your response.

I used the default Machinist X99 RS9 BIOS (see image
![IMG_20221213_191336](https://user-images.githubusercontent.com/120734198/208293909-13d20a42-76dd-4bbb-b74d-c35de13d8a72.jpg)
), so I asume that has no turbo unlocked and any undervolting setup.

Yesterday I watched your Youtube video about this motherboard and your recommendation to change to Huananzhi x99 8m-f BIOS,, and I did it with TU PEI -50/50mv version. Congrats for your application! It's awesome! However, there are still freezes... 😞

Ok, I'll check my RAM with the program you says and I'll back to comment the results. 

Finally, I have a couple of doubts. Can the bios change without a clean install of Windows 10 be meaningful? And, does it make sense to try inserting the two RAM modules in the other two (black) slots?

Many thanks!

**Comment by miyconst** [comment]
>Can the bios change without a clean install of Windows 10 be meaningful?

Yes, BIOS is a separate thing, works separately from Windows.

>And, does it make sense to try inserting the two RAM modules in the other two (black) slots?

Yes, it surely does make sense, if the system stops freezing with other RAM slots used - you have a defective RAM slot.

**Comment by Deifuss** [comment]
Hi again,

After more than 5 hours, Memtest86 has passed OK my RAM modules. After disabling turbo and power management features in BIOS, reinstalling a clean W10 and placing two RAM modules in other two slots, freezes seem to have disappeared.

I'll let a few days go by and reset the flashed BIOS to default to see if everything is still ok.

Many thanks, Miyconst!

**Comment by Deifuss** [comment]
Hi there,

I have been impatient and I have restores the installed BIOS back to default (huananzhi_x99-8m-tp-tu-pei-50-50) and it works like a charm, so I attribute the past freezes to a bad Windows installation or to some CPU pin that It wasn't quite right (I repositioned the entire CPU module).

Can close! Thank you!

**Comment by Deifuss** [comment]
Unfortunately, after a few hours It has freeze again...  I have had to unset Turbo and EIST in the BIOS. It seems that it does not suit it at all.

**Comment by miyconst** [comment]
You might have got a very unlucky CPU that can't even handle -50/50 MV offset, if you want to dig, you can make your own modification for -40/40 or even -30/30 MV then see if it works.

**Comment by Deifuss** [comment]
Yeah, I think I've had bad luck with this CPU.
I can confirm that the problem is specifically the turbo boost. By disabling it in the BIOS, the freezes disappear.
