### ISSUE TITLE
Kllisre X99 V205 bios puzzle 

### ISSUE THREAD

**Issue by Redstormz** [miyconst/Mi899#74]
Hi...I recently purchased a Kllisre X99 V205 motherboard (i think it has a C222 chipset instead of B85 on V201).

I wish to perform turbo unlock but I can't seem find a modified bios for it on Mi899. Any idea which bios is suitable or compatible for turbo unlock on this motherboard?

Many thanks in advance....

**Comment by miyconst** [comment]
As far as I know, the motherboard is compatible with the V201/202 BIOS options, but I can't guarantee that since I didn't test the motherboard myself.

**Comment by Redstormz** [comment]
Hi, Miyconst...

Thank you for your reply.... Are you saying that it is possible for C222 and B85 chipsets to have the same bios? I am asking because V205 has a C222 chipset whereas V201 has a B85 chipset.

**Comment by miyconst** [comment]
Yes, it's surely possible. Also all these versions come with random chipset, C222 or B85, it's not dedicated to a specific revision.
