### ISSUE TITLE
Support for Qiyida ED4 X99 ?

### ISSUE THREAD

**Issue by gingerbread233** [miyconst/Mi899#75]
I tried flashing the BIOS manually. The CPU speed (E5 2620 v3), is still the same. Either I did it wrong, or the Mainboard doesn't support turbo unlock. Other Chinese X99 boards are working fine with your software.

**Comment by miyconst** [comment]
Are you asking about this motherboard, but with two extra RAM slots? [🇬🇧 Review of Trash X99 (Kllisre, Machinist) LGA 2011-3 | E5-2620 V3 | Turbo Unlock | GTX 1660](https://youtu.be/mZHcdbmxI3s).

**Comment by gingerbread233** [comment]
Yes, it seem to be similar to the board in the video, it has 4 RAM slots, and 3 Sata connectors. Do you think flashing the "trash BIOS" will work? Because my own modification, doesn't show any improvements with all core boosting.

**Comment by miyconst** [comment]
It might work, but since I didn't test your motherboard, I can't guarantee any compatibility.

**Comment by gingerbread233** [comment]
Is it possible to provide you the BIOS dump, so you could modify it, and maybe add it to your repository if it works on my board?

**Comment by miyconst** [comment]
It's possible, but I don't guarantee that I will have time any time soon. Please also attach your motherboard's picture.

**Comment by gingerbread233** [comment]
[x99.zip](https://github.com/miyconst/Mi899/files/10327735/x99.zip)
unfortunately I only could dump the already modyfied BIOS (so"06F2" is already deleted), because I lost the original due to an OS error ( I had to reinstall Win 10). In the zip file there is the x99 bios dump and a jpg of the board. The full model name is Qiyida X99H ED4. Also I needed to download the toolbox again, I found out one of your links stopped working, wich worked few days ago, at:
https://miyconst.github.io/hardware/cpu/intel/2020/01/04/xeon-e5-2600-v3-turbo-boost-unlock.html
It's the link from: Method 1: Inject FFS driver straight into the BIOS.
From Microsoft One Drive:([x99-tu-ffs.zip](https://1drv.ms/u/s!AtZZXDjjb94k61IdfWbVDXsd9WJX?e=LmC613)
I hope you can help me out, maybe it will work to unlock the turbo boost on this board.

Thank you.

**Comment by gingerbread233** [comment]
Hello, 
I did some research and found modified BIOSes, someone already did it, I can confirm, that it is working fine on my board, maybe you can add it to your software without doing the work modify it by yourself. Please take a look:

https://vk.com/topic-113086402_48062678

**Comment by miyconst** [comment]
@gingerbread233 thank you for sharing the info, but I do not add BIOS that I have not verified personally.

**Comment by jonybhjkfy** [comment]
hola buenas mi placa es una  qiyida e5 2660 v3 d4 v10 cual es la bios que debo descargar?

**Comment by kfpciq-ship-it** [comment]
> مرحبًا، لقد أجريت بعض الأبحاث ووجدت BIOSes معدلة، وقد قام شخص ما بذلك بالفعل، ويمكنني التأكيد على أنه يعمل بشكل جيد على لوحتي، ربما يمكنك إضافته إلى برنامجك دون القيام بالعمل لتعديله بنفسك.

I have the same motherboard can you give me your BIOS
