### ISSUE TITLE
Atermiter X99 V201 Bios flash black screen 

### ISSUE THREAD

**Issue by Magikit** [miyconst/Mi899#77]
I am not sure why, but it seems like my Atermier X99 V201 is NOT compatible with Huananzhi X99-8M-F BIOS.

I flashed Huananzhi X99-8M-F TU 50-50 BIOS using Mi899, but got permanent black screen.

My chipset is S177 (H81) 

Help, i dont have any working bios for my motherboard.

**Comment by miyconst** [comment]
Did you backup your original BIOS before flashing X99-8M-F? If no, then you have to ask the seller to provide you the original BIOS.

**Comment by Magikit** [comment]
> 

Well, the problem is that I didn't make a backup, and I've had the motherboard for some time and I don't know who I bought it from, or rather another seller won't send me the bios, right?

**Comment by miyconst** [comment]
They may still send you the BIOS if you ask kindly enough :)

You can also try some BIOS options from this page - https://xeon-e5450.ru/socket-2011-3/x99-v201/

**Comment by Magikit** [comment]
I tried the one with the backup v201 designation but no changes, I noticed that if I have a wireless keyboard connected when I turn on the computer, it gives a sound signal, I think 5 beeps or 1 long beep and 5 short beeps

**Comment by miyconst** [comment]
>I tried the one with the backup v201 designation but no changes

You need to try different BIOS options to see which one would boot with your motherboard, you obviously have some unique revision.

>I think 5 beeps or 1 long beep and 5 short beeps

This usually indicates to not detected GPU. What is your full system spec?

**Comment by Magikit** [comment]
I will try other bios versions.  And damn it, I would have to at least get some other GPU to check if it could be a GPU, there is no one in my city, and maybe I'll order an old used one to try.

**Comment by Magikit** [comment]
The seller sent me the bios from this board and I uploaded it, the only thing that has changed is that the first green LED on the output ports side is lit on the GPU and there are no beeps. But there is no image anyway, is there a possibility that it will not display the image via hdmi? At the moment I don't have a hard drive connected because I had to give it to a friend.

**Comment by miyconst** [comment]
It should boot up and show something on the screen with no hard drives connected. Does the keyboard work once it's on?

**Comment by Magikit** [comment]
I connected the rgb keyboard and when turned on, it does not turn on the LEDs

**Comment by miyconst** [comment]
If you press Caps / Num Lock, does the LED indicator change its state?

**Comment by Magikit** [comment]
No reaction

**Comment by Magikit** [comment]
Maybe the processor?  Because the pins were straightened.  but the power section of the processor heats up and the processor is probably ok?

**Comment by miyconst** [comment]
The motherboard is dead, most likely, CPUs go out of order very seldomly.

**Comment by Magikit** [comment]
Damn, it was lying unused for so long time and broke down. Well, the processor works fine on other motherboard at my friend's because I got a processor from him, I know, but maybe some pin of the socket does not touch the processor and such a failure?

**Comment by miyconst** [comment]
Everything could be, you can to refit CPU, RAM, GPU, PSU.

**Comment by Magikit** [comment]
After a long struggle, it turned out that the chipset died, as stated by a more experienced service.
