### ISSUE TITLE
Remove Russian language 

### ISSUE THREAD

**Issue by SlimRG** [miyconst/Mi899#78]
Remove russian language and block app on russiian pc if you're with Yukranian People!

**Comment by miyconst** [comment]
The ruzzian language is already disabled a couple of releases ago.

![image](https://user-images.githubusercontent.com/6435556/216413551-f4118cec-af02-40b8-b728-4f34cc2af212.png)

How would you propose to block the app on ruzzian PCs'?

**Comment by LinerSRT** [comment]
> The ruzzian language is already disabled a couple of releases ago.
> 
> ![image](https://user-images.githubusercontent.com/6435556/216413551-f4118cec-af02-40b8-b728-4f34cc2af212.png)
> 
> How would you propose to block the app on ruzzian PCs'?

Заблокируй себе мозг, укропитек

**Comment by miyconst** [comment]
Google translate of the @LinerSRT's [message](https://github.com/miyconst/Mi899/issues/78#issuecomment-1416706556) for those naїve Europeans and Americans who still believe that there are good ruzzians:

>Заблокируй себе мозг, укропитек
>Block your brain, dill

![image](https://user-images.githubusercontent.com/6435556/216760638-716a224a-f21b-4c6b-b67e-2c3b8cf9bd76.png)

**Comment by jult** [comment]
> Remove russian language and block app on russiian pc if you're with Yukranian People!

Wow, that's just pathetic. To bring those lies to a software/dev forum, how low can you go? As if ALL civilians are complicit in what their governments are doing. Besides, you're incorrectly informed. You have no idea what you're even writing/talking about, do you? Go educate yourself, why don't you? https://odysee.com/@NotTheBoilingFrog:f/What-you-don't-know-about-the-war-in-Ukraine_2022-02-27_20-24-28:a
And I have collected a couple of videos for you to listen/view: https://www.youtube.com/playlist?list=PL1StK4aSSWe51wLPj5b2uFyWfmVhDOELi

**Comment by miyconst** [comment]
@jult you are either living in an illusion or you are a russian troll, either is not good for you, but if you are open for a factual discussion - ping me on [Discord](https://discord.gg/nTemxwMn).

All the videos you posted are full of lies with a fraction of truth and as a Ukrainian I know what happened and I know what russo-nazis did in Ukraine.

**Comment by jult** [comment]
> @jult you are either living in an illusion or you are a russian troll, either is not good for you, but if you are open for a factual discussion - ping me on [Discord](https://discord.gg/nTemxwMn).
> 
> All the videos you posted are full of lies with a fraction of truth and as a Ukrainian I know what happened and I know what russo-nazis did in Ukraine.

In fact, and you damn well know it by now, you are the one lying. Most Ukrainians (more than 80%) are (still!) pro Russian language, now even more so than prior to 2014. They hate Zelenskyy. Again, you have no clue what happened, probably too young or ill informed. And you removed the links, because you're afraid of the truth here. https://www.thepostil.com/the-military-situation-in-the-ukraine/ Seriously, history will prove you wrong so hard it's going to be problematic for many who are so convinced about their fake news and fake NATO-war propaganda to even avoid landing a deep depression.

**Comment by miyconst** [comment]
@jult maybe you live in Ukraine? Maybe you have friend and family in Ukraine? Maybe you have friends and family who suffered ruzzian occupation? No? Then what truth are you talking about? Your imagination and parallel reality does not qualify for truth.

I still don't see you on Discord, ping me there if you aren't afraid of factual discussion.

**Comment by jult** [comment]
> The ruzzian language is already disabled a couple of releases ago.
> 
> ![image](https://user-images.githubusercontent.com/6435556/216413551-f4118cec-af02-40b8-b728-4f34cc2af212.png)
> 
> How would you propose to block the app on ruzzian PCs'?

You can't even spell Russian correctly, and you expect to make decisions based on language?

**Comment by mcirsta** [comment]
It is open source yes but the author can do whatever he pleases.
If anyone wants anything else they can maintain their own version.

**Comment by jult** [comment]
LOL, so are you also removing the English language now that the US/UK/NATO war machine has been judged by the ICJ for sponsoring and encouraging genocide and war-crimes in Gaza? By the way, the US already committed war-crimes for decades on end (and waaaay more deaths than Russia ever has). Starting with the needless nuclear bombs on Hiroshima and Nagasaki.

**Comment by git4rker** [comment]
inviting racism and war into open-source software doesn't make sense...
