### ISSUE TITLE
X99H V1.41 Turbo Unlock

### ISSUE THREAD

**Issue by Redstormz** [miyconst/Mi899#80]
Hi, 

Does anyone know which modified bios is suitable for this Envinda X99H V1.41 motherboard for turbo unlock? I can't seem to be able to find one...many thanks in advance...

![IMG_20230220_205411](https://user-images.githubusercontent.com/120765124/220114686-175d932c-0ac6-4d15-a7f1-fa2ba59270b3.jpg)

**Comment by miyconst** [comment]
I am sorry to say, but I strongly recommend to stay away from this motherboard and don't know what BIOS is compatible. These videos explain it all:

- [🇬🇧 ZX_99EV3, ZX_MINX9D4, ZX_DU99D4, ZX_99D3A4 – please do not buy these motherboards](https://youtu.be/7Pyef_ySHwo).
- [🇬🇧 Review of Trash X99 (Kllisre, Machinist) LGA 2011-3 | E5-2620 V3 | Turbo Unlock | GTX 1660](https://youtu.be/mZHcdbmxI3s).

**Comment by Redstormz** [comment]
Hi...sorry for the late reply... unfortunately I have already bought this motherboard and cannot return it. So, you mean to say that there's no way to perform turbo boost unlock for this motherboard for now?

**Comment by Redstormz** [comment]
> I am sorry to say, but I strongly recommend to stay away from this motherboard and don't know what BIOS is compatible. These videos explain it all:
> 
> * [🇬🇧 ZX_99EV3, ZX_MINX9D4, ZX_DU99D4, ZX_99D3A4 – please do not buy these motherboards](https://youtu.be/7Pyef_ySHwo).
> * [🇬🇧 Review of Trash X99 (Kllisre, Machinist) LGA 2011-3 | E5-2620 V3 | Turbo Unlock | GTX 1660](https://youtu.be/mZHcdbmxI3s).

hi, thanks for your feedback...but unfortunately I have already bought this motherboard and cannot return it. Is there really no way to do a turbo unlock for this motherboard? It has a Q85 chipset and the current bios details are as follows:-

![IMG_20230223_205755](https://user-images.githubusercontent.com/120765124/220959551-e238f81e-0f79-4678-aae3-4fb7fb47f2b5.jpg)

Any help is much appreciated.... thanks in advance

**Comment by miyconst** [comment]
You can follow this guide: [🇬🇧 X99 LGA 2011-3 in 2021 – AliExpress shopper guide, Huananzhi, JingSha, Machinist, Xeon E5 V3/V4](https://youtu.be/GAg-sReQ8wU).
