### ISSUE TITLE
Machinist X99 D8 MAX Dual CPU Bios update

### ISSUE THREAD

**Issue by alexnetdoc** [miyconst/Mi899#82]
Hi there,

I have ordered Machinist X99 D8 Max Dual CPU, but unfortunately I could not find this motherboard in Mi899 tool. Do you know what Bios can I use to try and flash with -50mv and unlock turbo boost?

Here's the link to the motherboard
https://www.aliexpress.com/item/1005002977212126.html

![image](https://user-images.githubusercontent.com/6435556/222099679-dfa15f76-9d38-4eaf-9a2b-419b2bb3bd99.png)

Thank you in advance!
Alex

**Comment by miyconst** [comment]
I am sorry to disappoint, but I have not yet tested this board and don't know much about it.

**Comment by alexnetdoc** [comment]
Thank you, no worries. When I will receive it, I will check what kind of Architecture it uses and how it works... hopefully to give some feedback. NOTE: I will be using E5-2650L x2 CPU's here. 
I like low power systems and high temps are not my cup of tea.:)

**Comment by miyconst** [comment]
>I will be using E5-2650L x2 CPU's here.

I assume you mean Xeon E5-2650L V3. Anyway, I am very unsure why would someone opt to go with two low-powered and low-performance Xeons in an expensive and unreliable dual socket LGA 2011-3 motherboard instead of buying a modern single socket solution that provides better performance and much better efficiency.

**Comment by alexnetdoc** [comment]
I am enthusiast and IT professional. This is a workstation for every day use with the possibilities of "What it can do". Not for gaming. As I have never worked properly with Xeons, especially on ultra budget workstation, that interests me :)
as for the reasons of LGA-2011-3 - ECC RAM and 4-8 channels of memory is the breaking point for me.

**Comment by LiftedZ** [comment]
> I am enthusiast and IT professional. This is a workstation for every day use with the possibilities of "What it can do". Not for gaming. As I have never worked properly with Xeons, especially on ultra budget workstation, that interests me :) as for the reasons of LGA-2011-3 - PCIE Lane count (using ASUS X16 SSD card), ECC RAM and 4-8 channels of memory is the breaking point for me. Moreover I was doing a Decoding operation with my E5-2650L v3 CPU vs Ryzen 5 3600 and the results was only 1 min 23 sec. difference vs 4 times cheaper price for Xeon :)

I have a bricked BIOS from the time of purchase, didn't mod anything. Could you share your original BIOS with me?

**Comment by alexnetdoc** [comment]
Hi,

I am on vacation right now. It might take few weeks before I am at home and extract the BIOS. I'll let you know when I am succesfull.

Sorry to hear you bricked yours!

Alex
------- Original Message -------

**Comment by codylay24** [comment]
alexnetdoc can i get a copy of that bios as well please

**Comment by LiftedZ** [comment]
Thank you, Alex, but don't worry about it.
I threw it away now.

С праздниками :-)
