### ISSUE TITLE
Add support for JGINYUE  X99 8D4

### ISSUE THREAD

**Issue by hany-mamdoh** [miyconst/Mi899#83]
Add support for JGINYUE  X99 8D4 please
thanks for your hard work

https://www.aliexpress.com/item/1005005320388968.html

![image](https://user-images.githubusercontent.com/6435556/225804722-a23a9a1d-f56e-49e8-960c-b6b2af9fce6f.png)

**Comment by miyconst** [comment]
I am really sorry to disappoint, but most likely X99-8D4 won't be added for the following reasons:

- The motherboard is seriously overpriced and I can't afford wasting this much money.
- All recent X99 motherboards from Jginyue come with a horrible BIOS and the only salvation is a compatible Huananzhi BIOS, but this motherboard seems to be unique and unlikely to work with Huananzhi BIOS.
- Quality concerns.

**Comment by AnxHall** [comment]
@miyconst i have 2 X99-8D4, can i help? i have the original bios and the updates from, u can just release for support bios reflash when someone needs  

last update:
` http://down1.jginyue.com/uploads/x99%208D4%202.5G%E6%96%B0%E7%89%88%E6%9C%AC%E9%B8%A1%E8%A1%80+%E5%8E%9FBIOS.rar `
