### ISSUE TITLE
Mi899-1.2.9 - Opens in the BIOS setup on the Recovery menu

### ISSUE THREAD

**Issue by ricardoballaro** [miyconst/Mi899#84]
I updated the BIOS of my HUANZHI F8 Nova, but every time I turn off and on the computer, it opens in the BIOS setup on the Recovery menu. Do you know what could be causing this?
*Mi899-1.2.9

**Comment by miyconst** [comment]
Your motherboard's revision is not compatible with the BIOS you have flashed, you need to restore the original BIOS.

**Comment by ricardoballaro** [comment]
But it's working, if I exit the BIOS setup the system starts normally.

**Comment by miyconst** [comment]
If it goes into the recovery mode - it doesn't work properly.
