### ISSUE TITLE
ZX-DU99D4 Motherboard not Listed

### ISSUE THREAD

**Issue by DannyT43** [miyconst/Mi899#86]
Having issues with RAM 64Gb using 4 slots runs fine but 128Gb using 8 slots gives a bios error code of 6d. 
Was hoping a bios update would fix this?
Also Resizeable Bar Support would be useful.  

System Specs
AliExpress X99 Motherboard ZX-DU99D4 v1.31
Dual Intel Xeon E5 2690 V4
Atermiter 64GB (4x16GB) DDR4 ECC 3200Mhz
(only sees it as 2400Mhz in windows)
MSI Gaming X Nvidia RTX3060
nvme m.2 Drives
Gigabyte 128GB Boot Drive
Kioxia 240GB
Sata m.2 Drives
San Disk X600 128GB
2.5" Drives
Kingston 228GB SSD
Western Digital 500GB (Ex Laptop)
HGST 1000GB (Ex PS3)
3.5" Drives
Western Digital 500GB Blue
Western Digital 500GB Blue
Hitachi 500GB
NAS Refs RAID 0 Drives
Seagate IronWolf 10TB
Seagate IronWolf 10TB
Seagate IronWolf 10TB
Seagate IronWolf Pro 10TB
Fideco USB 3.0 HDD Docking Station
Seagate 500GB
Seagate 500GB
Total Data Storage Capacity Approx 45TB
Phanteks 140mm Case Fans x3
White Led 120mm Case Fans x4
Aliexpress 92mm 4 Heatpipe Tower Coolers x2
Corsair 850RM Gold Power Supply

**Comment by jwagnervaz** [comment]
I have the same board and rev, and mod the bios to support all 8 slots. If you need check my repository.

**Comment by miyconst** [comment]
Hi @jwagnervaz! Are you a BIOS modder? Would you be able to help me with different mods if needed?

**Comment by jwagnervaz** [comment]
> Hi @jwagnervaz! Are you a BIOS modder? Would you be able to help me with different mods if needed?

Yes sure, my email is jwagnervaz@gmail.com

**Comment by Parliamentarian** [comment]
Set Mmio base to 2T when using 128gb otherwise youll get strange issues.
