### ISSUE TITLE
X99 RS9 with q87 chipset and E5 2640 V3. I get random screen freezes. Which BIOS?

### ISSUE THREAD

**Issue by yaggoto** [miyconst/Mi899#87]
Hi, which Bios will be good for Machinist X99-RS9 + E5 2640 V3 to make turbo unlock? Huananzhi X99-8M-F b85 BIOS will work?

Using original bios.

**Comment by miyconst** [comment]
When it comes to the Chinese motherboards, there is absolutely no guarantee about BIOS compatibility, but X99-RS9 should work with X99-8M-F BIOS.

Still, if your motherboard freezes with the stock BIOS, I really doubt that Huananzhi BIOS will do any better, it's most likely a hardware issue. Either motherboard, or RAM, or CPU, or USB attached devices, it could even be CPU, but most likely it's the motherboard.
