### ISSUE TITLE
HUANANZHI X99 QD4 2X16GB DDR4 2133 E5-2677V4 slow TDP rise

### ISSUE THREAD

**Issue by fish7221** [miyconst/Mi899#89]
Hello Friends.
I'm having somewhat lack of understanding/problem with my setup :
Motherboard : HUANANZHI X99 QD4
Ram : 2X16GB DDR4 2133 ECC
Cpu :  E5-2677V4
Cooler : 4 heatpipes 90mm fan
I've flashed the non-undervoltage mi899 bios, And played a bit with overclock, But cpu never gets over 83W TDP in hwinfo64.
It's also doesn't go fully to 3.5GHZ on all cores (The best I got is 3.456GHZ (Effecitve 3.484GHZ)).
When I run cinebench 20, It doesn't go instanatly to max cpu speed, But it takes him about 60 seconds to get there (The TDP starts around 60W and after a minute reaches 83W).
Temps are very good (under 63C in stress test).
Maybe it's a limit/protection in the motherboard hardware I'm not aware of, Or my lack of understanding in the overclock settings.
I would appreciate if someone can tell me what to set in bios so the cpu can reach it's 135W and have the proper voltage needed for that.
Thank you

**Comment by miyconst** [comment]
Think this particular issue is not related to Mi899 itself, thus I would recommend you to join my Discord instead:  https://discord.gg/hVJQS36E

From your description it's unclear what BIOS you flashed, but V4 Xeons are not compatible with Turbo Boost Unlock.
