### ISSUE TITLE
x99 F8 - 2699 -v3

### ISSUE THREAD

**Issue by bellessecretsshow** [miyconst/Mi899#90]
Hi i know this is a very late post but i a totally stumped. 

I tried the following Bios files  
hz-x99f8.tu.ffs-20
hz-x99f8.tu.ffs 

now i can flash both to the motherboard  and i do get 3.30ghz  on all cores for the turbo.    the hz-x99f8.tu.ffs-20 was more stable in windows.    However i am getting major issues with the bios. 

Upon restart  the motherboard makes a horrible noise  and loads the bios up right away  on a screen that isn't normally present   Recovery.      If i esc out windows loads.     I have tried the  load defaults  save and reset   but i get this on every boot up.  

I am a bit stumped as i then followed  the manual guide   removed the 06f2 and turned off the c states  and tried the bios at that point however windows freezes after an hour.  but i don't get the  boot up issue. 

i have flashed the backup  back to the motherboard  and i am at a bit of a loss if anyone could recommend how i should proceed. 

The machine is an editing pc so the boost is massive for us. 

Many Thanks 

Chrissy

**Comment by miyconst** [comment]
Unfortunately, you have another revision of X99-F8 motherboard that is not fully compatible with the original BIOS available in Mi899. The only option for you is to mod the original BIOS that your motherboard came with.

**Comment by bellessecretsshow** [comment]
could you recommend a board?   
dataloss isnt an issue  as the f8 support vtd so have immou  as proxmox sits behind it.   so if the board fails  at most we loose an hours work  the cpu is so fast you would never know it was on top of a hypervisor yet it runs just like a desktop machine 

all we need is a board that can take 
2699 v3 or v4
64gb 4x 16gb ddr4
ideally 3 pci e slots for the gpu and hba 

i loaded win 10 so i could get the bios update on the board, and tested with cyber punk   for a good 8 hours.   the -20 mV one was stable all that time it just wouldnt work in the bios right. 

If there is a board that can run those chips   i am happy to have a recommendation.

**Comment by miyconst** [comment]
Huananzhi X99-F8 is one of the best if not the best offer from China, but from my experience, I couldn't make Turbo Boost Unlock working with Proxmox, no matter what I try, with Turbo Boost Unlock the board would lock here or there.

If you want something quality and reliable then go with the used workstations, like I have already suggested, Dell T5810 for example.
