### ISSUE TITLE
bios huananzhi f8d 

### ISSUE THREAD

**Issue by XxGTK** [miyconst/Mi899#91]
hello I'm looking for a way to unlock the bios on my huananzhi f8d x99 motherboard. Do I need a ch431a programmer? and where can I get a stable and reliable bios for my two intel xeon e5 2678 v3 cpus? thank you.

**Comment by miyconst** [comment]
This is a Mi899 repository but your question is unrelated. For general help and info, please use my Discord: https://discord.gg/rCSXGBBc
