### ISSUE TITLE
Machinist X99 PR9 supported ?

### ISSUE THREAD

**Issue by NewRedsquare** [miyconst/Mi899#92]
Hello,

Do you know if machinist X99 PR9 is compatible with any of the existing BIOSes made for other similar board ?

Do you want me to send informations about the hardware (chipset etc.) ?

Thanks

**Comment by NewRedsquare** [comment]
> I have not yet tested the motherboard, thus I can't comment. In general, the motherboard looks like something I would strongly recommend staying away from.

What makes you afraid of it ?

**Comment by miyconst** [comment]
>What makes you afraid of it?

Pathetic VRM, pathetic VRM radiator, and the look that is very close to other motherboards known for their bad quality.
