### ISSUE TITLE
Hello, I need some advice with a xeon E5 2696 v3 + Motherboard Machinist E5 Mr9a pro v3, Will it hold up to a light turbo boost?

### ISSUE THREAD

**Issue by ErzzaGG** [miyconst/Mi899#93]
I have a xeon E5 2696 v3 + Machinist E5 Mr9a pro v3 board working in dual channel

and I can't find a light turbo boost to this combination
I already changed the factory bios x99 mr9a for a x99 8m f tp
And it works fine but each core runs at a maximum of 2.3 Ghz

I was wondering if it was possible to turbo boost it and push it to 2.8 or 3 ghz or is this motherboard considered very unstable?
I have the program you use to change bios
but I only put one that does not include turbo boost
Because I don't know which is a stronger turbo boost and which is lighter.
![WhatsApp Image 2023-11-09 at 2 37 25 PM](https://github.com/miyconst/Mi899/assets/150381505/9e27e04b-7799-487c-845e-58a6f2bce8b6)

**Comment by miyconst** [comment]
You can use the safe option with `-50/50mv` your motherboard should hold it. Most CPUs can also handle `-70/50mv` but any further reduction may lead to system instability.

**Comment by ErzzaGG** [comment]
Ty so much
