### ISSUE TITLE
Support for IWONGOU X99 Motherboard?

### ISSUE THREAD

**Issue by Dhuks** [miyconst/Mi899#94]
HI, ive recently seen this motherboard on Aliexpress(https://www.aliexpress.com/item/1005006152052431.html) The price for such a motherboard is very competitive and so ive wondered if you could add support for the motherboard, of which bios should i flash for the motherboard.

**Comment by miyconst** [comment]
I have not yet tested this motherboard, thus I can't add support to Mi899, once it's tested - it will be added. If you want to speed the process up - buy me the motherboard for testing.

![image](https://github.com/miyconst/Mi899/assets/6435556/d5c71851-30eb-4a6a-b217-241b51d68f13)

**Comment by HBGamer10** [comment]
I just checked and I am pretty sure that this motherboard is the same as the Qiyida x99-qd4 which Miyconst reviewed a while back
