### ISSUE TITLE
Jingsha Dual X99 Z8, is it covered by the bios for the single core socket in mi988? Also about Fivr/SVID

### ISSUE THREAD

**Issue by jimc4893** [miyconst/Mi899#95]
Hi guys. 

New to the platform but I have a Jingsha Dual Z8 and I'm wondering if the bios available for the D8 is compatible? I am also concerned with the best bios not being from a Jingsha board, is it okay to use them even if it's not from the same board?

Also i came across this git repo about the FIVR/SVID patch (https://github.com/Koshak1013/HuananzhiX99_BIOS_mods) but never heard about it on the channel or in english. I checked out a bios patched from vk.com and there are fivr options, that apparently are put through ultimate patcher, that lead to much higher frequency and tdp utilization.

I was just wondering why these are not patched into the bios on mi899?

thank you

**Comment by miyconst** [comment]
>I have a Jingsha Dual Z8 and I'm wondering if the bios available for the D8 is compatible?

As far as I know, it's not compatible.

>Also i came across this git repo about the FIVR/SVID patch (https://github.com/Koshak1013/HuananzhiX99_BIOS_mods) but never heard about it on the channel or in english.

I have mentioned it a couple of times and there are several BIOS options in Mi899 that I took from `Koshak1013`.

>... that apparently are put through ultimate patcher, that lead to much higher frequency and tdp utilization.

The FIVR/SVID patch breaks CPU's TDP calculation and restriction, it leads to massive increase in power draw and VRM abuse. With the Chinese motherboards it often leads to the death of the motherboard.
