### ISSUE TITLE
MR9A rev. 2 Keeps Crashing with any UV settings

### ISSUE THREAD

**Issue by uncledoody** [miyconst/Mi899#96]
Miyconst,

I am a huge fan of your channel and so appreciative of the effort you put into x99 for us.

I recently purchased a Machinist MR9A Rev 2: https://www.aliexpress.com/item/1005006129861639.html

When I use the 1.0 Bios with TU and -50/50 or even with -100/50, the computer will boot, but within 15s to up to 2-3 minutes, it will freeze.  It won't crash, but the OS will freeze in place.  Any idea why?  I am not using name brand RAM, but the RAM does seem to be allowing it to boot.  I don't know nearly as much about this stuff as you do, but in my head, it seems like something is overheating because if I leave it turned off long enough, it will go longer before it freezes.

**Comment by miyconst** [comment]
Hi there. Please watch my latest video, there you may find answers to your questions: [🇬🇧 Turbo Boost Unlock in 2023 – everything you need to know and more](https://youtu.be/IsgBQ0ZMxYY).

In short, the reasons could be:

- Wrong CPU C-State configuration.
- CPU and/or VRM are not able to withstand TBU.
- The motherboard is defective.
- The RAM is defective.
- The system is corrupt.
