### ISSUE TITLE
Support   for  HUANANZHI QD4  MOTHER BOARD   

### ISSUE THREAD

**Issue by dangchuif16** [miyconst/Mi899#97]
HELLO   is there  Support  bios compatible   for  HUANANZHI QD4  MOTHER BOARD  

[![image](https://github.com/miyconst/Mi899/assets/6435556/5ef2b4ef-3a04-410b-b219-2f5a844f981a)](https://s.click.aliexpress.com/e/_DcfGeCl)

i don t find   on  MI899  LIST 

THANKS   FOR YOU HELP

**Comment by miyconst** [comment]
Probably you are using an old version of Mi899, the latest version has a whole range of available options, see the [`Model.json`](https://github.com/miyconst/Mi899/blob/master/src/Mi899.Data/Model.json#L3326) file.

**Comment by dangchuif16** [comment]
THANKS FOR  YOU ANSWER    STRANGE  I  SEARCH  THIS MORNING ON Mi899  2.8   latest  VERSION
AND I  don t   find  may  if i change only  the  file Model.json  is better

i see  on list    the web link  for  HUNANZHI   QD4 :     https://github.com/miyconst/Mi899/raw/master/src/Mi899.Data/Bioses/huananzhi-x99-qd4.rom.zip

i hope  is  mod bios  specially   with   turbo boost  actived

**Comment by miyconst** [comment]
Each BIOS option has a description, it specifies what is activated and what's not.
